import type { HarnessCatalog } from "./types.js";

/** Amp Code settings catalogue — researched 2026-08-11 from live settings.json + lowerer + manual. */
export const ampCodeCatalog: HarnessCatalog = {
  harness: "amp-code",
  displayName: "Amp Code",
  binaryNames: ["amp"],
  binaryEnvVars: ["PRISM_WORKFLOW_AMP_BIN", "AMP_SETTINGS_FILE"],
  globalRoot: "~/.config/amp/",
  projectRoot: ".agents/",
  settingsFiles: [
    { path: "settings.json", format: "json", primary: true },
    {
      path: "AGENTS.md",
      format: "md",
      note: "Rules; Prism marker regions (<!-- --- prism:... begin/end --- -->)",
    },
    {
      path: ".amp/settings.json",
      format: "json",
      note: "Workspace-scoped settings (project root, not under .agents/); merges over user config",
    },
    {
      path: "settings-haiku.json",
      format: "json",
      note: "Optional alternate settings profile (user); not Prism-managed",
    },
  ],
  scanDirs: ["plugins", "skills", "commands", "toolbox"],
  prismNamespaceMarkers: ["prism-generated-", "prism-agent-"],
  fields: [
    {
      key: "amp.dangerouslyAllowAll",
      label: "Dangerously allow all tools",
      type: "boolean",
      file: "settings.json",
      prismTouch: "none",
      description:
        "Bypasses permission prompts. Workflow worker copies settings to a temp file and forces true for permissive/full-access only; never writes the durable user file.",
      cousin: "permission-posture",
    },
    {
      key: "amp.permissions",
      label: "Tool-level permissions",
      type: "array",
      file: "settings.json",
      prismTouch: "none",
      description:
        "Ordered rules: { tool, matches?, action: allow|reject|ask }. First match wins. Editable via `amp permissions`.",
      cousin: "permission-posture",
    },
    {
      key: "amp.mcpServers",
      label: "MCP servers",
      type: "object",
      file: "settings.json",
      prismTouch: "none",
      description:
        "Map of server id → { command, args } or { url }. Supports ${ENV} interpolation. Workspace servers under .amp/settings.json require trust.",
    },
    {
      key: "amp.guardedFiles.allowlist",
      label: "Guarded files allowlist",
      type: "array",
      file: "settings.json",
      prismTouch: "none",
      description: "Paths Amp may edit even when guarded-file checks apply.",
    },
    {
      key: "amp.tools.stopTimeout",
      label: "Tool stop timeout (seconds)",
      type: "number",
      file: "settings.json",
      prismTouch: "none",
    },
    {
      key: "amp.tools.disable",
      label: "Disabled tools",
      type: "array",
      file: "settings.json",
      prismTouch: "none",
      description: "Documented in Amp CLI guides; may be absent from a given install.",
    },
    {
      key: "amp.experimental.tools",
      label: "Experimental tools",
      type: "array",
      file: "settings.json",
      prismTouch: "none",
    },
    {
      key: "amp.internal.model",
      label: "Internal model override",
      type: "string",
      file: "settings.json",
      prismTouch: "none",
      description: "e.g. anthropic:claude-haiku-4-5-20251001. Workflow models use CLI --mode deep|rush instead.",
      cousin: "modelspace",
    },
    {
      key: "amp.internal.visibleModes",
      label: "Visible modes",
      type: "array",
      file: "settings.json",
      prismTouch: "none",
      description: "UI mode list (e.g. rush, free-next2). Workflow CLI accepts --mode deep|rush only.",
      cousin: "modelspace",
    },
    {
      key: "amp.internal.showCost",
      label: "Show cost",
      type: "boolean",
      file: "settings.json",
      prismTouch: "none",
    },
    {
      key: "amp.tryOpus",
      label: "Try Opus",
      type: "boolean",
      file: "settings.json",
      prismTouch: "none",
    },
    {
      key: "amp.anthropic.toolSearchTool.enabled",
      label: "Anthropic tool-search tool",
      type: "boolean",
      file: "settings.json",
      prismTouch: "none",
    },
    {
      key: "amp.notifications.enabled",
      label: "Notifications",
      type: "boolean",
      file: "settings.json",
      prismTouch: "none",
      description: "Documented in Amp guides; may be absent from a given install.",
    },
    {
      key: "amp.commands.allowlist",
      label: "Command allowlist (legacy)",
      type: "array",
      file: "settings.json",
      prismTouch: "none",
      description: "Older CLI guide key; tool-level amp.permissions is the current surface.",
    },
    {
      key: "amp.commands.strict",
      label: "Command allowlist strict",
      type: "boolean",
      file: "settings.json",
      prismTouch: "none",
    },
  ],
  refresh: {
    lastResearched: "2026-08-11",
    procedure: [
      "Run `amp --help` / `amp --version` (or $PRISM_WORKFLOW_AMP_BIN)",
      "Read ~/.config/amp/settings.json top-level keys (redact secrets / API keys in mcp URLs)",
      "Note workspace .amp/settings.json if present in a sample project",
      "Confirm AGENTS.md still uses <!-- --- prism:... begin/end --- --> marker regions",
      "List plugins/prism-generated-*.ts and skills/prism-agent-* layout",
      "Re-read src/compile/lowerers/amp-code.ts + workflow-amp-worker.ts for CLI flags and permission temp-file behavior",
      "Cross-check https://ampcode.com/manual (settings, permissions, MCP)",
      "Update fields[] and lastResearched",
    ],
    sources: [
      "amp --help / amp --version",
      "amp permissions (edit/add/test)",
      "~/.config/amp/settings.json",
      "~/.config/amp/AGENTS.md",
      ".amp/settings.json (workspace)",
      "https://ampcode.com/manual",
      "src/harnesses.ts",
      "src/lowerer-capabilities.ts",
      "src/compile/lowerers/amp-code.ts",
      "src/workflow-amp-worker.ts",
      "src/refresh.ts (rules marker regions + compile-managed commands)",
    ],
  },
  notes: [
    "Prism does not whole-file own settings.json. Workflow may write a temp settings copy with amp.dangerouslyAllowAll for permissive runs (AMP_SETTINGS_FILE / --settings-file).",
    "Rules install as marker regions on AGENTS.md (global ~/.config/amp/AGENTS.md; project via harness project rules path).",
    "Compile emits plugins/prism-generated-<plugin>.ts (global) or <project>/.amp/plugins/prism-generated-<plugin>.ts (project). Commands/tools/hooks use native amp.registerCommand / registerTool / amp.on — not settings patches.",
    "Compiled agents lower as skills/prism-agent-<name>/SKILL.md (role skills); no native Amp agent config surface.",
    "Harness projectConfigPath is .agents/ (skills + AGENTS.md routing); native Amp workspace settings/plugins also use .amp/ at the project root.",
    "commands/ under the Amp root holds native markdown commands (user/legacy); Prism-managed commands register via generated plugins, not that directory.",
    "Workflow models: deep | rush via --mode (assertAmpWorkflowMode). Default detection model: rush.",
    "Managed/enterprise override path (outside Prism): macOS /Library/Application Support/ampcode/managed-settings.json.",
  ],
};
