import type { HarnessCatalog } from "./types.js";

/**
 * Antigravity CLI (`agy`) settings catalogue — researched 2026-08-11 from
 * live ~/.gemini/antigravity-cli/settings.json, official CLI reference,
 * builtin customization docs, and Prism lowerer/harness sources.
 */
export const antigravityCliCatalog: HarnessCatalog = {
  harness: "antigravity-cli",
  displayName: "Antigravity CLI",
  binaryNames: ["agy"],
  binaryEnvVars: ["PRISM_WORKFLOW_ANTIGRAVITY_BIN"],
  globalRoot: "~/.gemini/antigravity-cli/",
  projectRoot: ".agents/",
  settingsFiles: [
    {
      path: "settings.json",
      format: "json",
      primary: true,
      note: "CLI/TUI preferences; Prism does not whole-file own or region-patch this file",
    },
    {
      path: "~/.gemini/config/mcp_config.json",
      format: "json",
      note: "Global MCP server map (mcpServers); empty on this machine at research time",
    },
    {
      path: "keybindings.json",
      format: "json",
      note: "Optional; created only when user runs /keybindings",
    },
    {
      path: "antigravity-oauth-token",
      format: "other",
      note: "secrets — never display",
    },
    {
      path: "~/.gemini/settings.json",
      format: "json",
      note: "Parent Gemini auth surface (security.auth.selectedType); not Prism-owned",
    },
    {
      path: "~/.gemini/trustedFolders.json",
      format: "json",
      note: "Trust map used by broader Gemini/Antigravity surfaces",
    },
  ],
  scanDirs: ["plugins", "skills", "mcp", "builtin"],
  prismNamespaceMarkers: ["prism-generated-"],
  fields: [
    {
      key: "model",
      label: "Model",
      type: "string",
      file: "settings.json",
      prismTouch: "none",
      cousin: "modelspace",
      description:
        "Display-name model string (e.g. \"Gemini 3.5 Flash (High)\"); also settable via /model and --model",
    },
    {
      key: "toolPermission",
      label: "Tool permission preset",
      type: "enum",
      enumValues: [
        "request-review",
        "proceed-in-sandbox",
        "always-proceed",
        "strict",
      ],
      file: "settings.json",
      prismTouch: "none",
      cousin: "permission-posture",
      description:
        "Global safety preset; TUI /permissions and --dangerously-skip-permissions override per session",
    },
    {
      key: "artifactReviewPolicy",
      label: "Artifact review policy",
      type: "enum",
      enumValues: ["asks-for-review", "agent-decides", "always-proceed"],
      file: "settings.json",
      prismTouch: "none",
    },
    {
      key: "allowNonWorkspaceAccess",
      label: "Allow non-workspace access",
      type: "boolean",
      file: "settings.json",
      prismTouch: "none",
      description: "Permit file tools outside recognized Git/workspace roots",
    },
    {
      key: "enableTerminalSandbox",
      label: "Terminal sandbox",
      type: "boolean",
      file: "settings.json",
      prismTouch: "none",
      description:
        "OS containment for agent shell commands (nsjail / sandbox-exec / AppContainer)",
    },
    {
      key: "trustedWorkspaces",
      label: "Trusted workspaces",
      type: "array",
      file: "settings.json",
      prismTouch: "none",
      description:
        "Live key: absolute path allowlist for workspace trust (observed on disk; not in public settings table)",
    },
    {
      key: "colorScheme",
      label: "Color scheme",
      type: "enum",
      enumValues: [
        "light",
        "solarized light",
        "colorblind-friendly light",
        "dark",
        "solarized dark",
        "colorblind-friendly dark",
        "tokyo night",
        "terminal",
      ],
      file: "settings.json",
      prismTouch: "none",
    },
    {
      key: "altScreenMode",
      label: "Alternate screen mode",
      type: "enum",
      enumValues: ["default", "always", "never"],
      file: "settings.json",
      prismTouch: "none",
    },
    {
      key: "notifications",
      label: "Desktop/terminal notifications",
      type: "boolean",
      file: "settings.json",
      prismTouch: "none",
    },
    {
      key: "showTips",
      label: "Show tips",
      type: "boolean",
      file: "settings.json",
      prismTouch: "none",
    },
    {
      key: "showFeedbackSurvey",
      label: "Show feedback survey",
      type: "boolean",
      file: "settings.json",
      prismTouch: "none",
    },
    {
      key: "editor",
      label: "External editor",
      type: "string",
      file: "settings.json",
      prismTouch: "none",
      description: "auto | vim | emacs | custom $EDITOR label",
    },
    {
      key: "editorMode",
      label: "Prompt editor mode",
      type: "enum",
      enumValues: ["default", "vim"],
      file: "settings.json",
      prismTouch: "none",
    },
    {
      key: "vimInsertFirst",
      label: "Vim insert-first",
      type: "boolean",
      file: "settings.json",
      prismTouch: "none",
      description: "Requires editorMode=vim",
    },
    {
      key: "enableTelemetry",
      label: "Enable telemetry",
      type: "boolean",
      file: "settings.json",
      prismTouch: "none",
    },
    {
      key: "useG1Credits",
      label: "Use G1 credits",
      type: "boolean",
      file: "settings.json",
      prismTouch: "none",
      description: "External builds only; spend personal credits past plan quota",
    },
    {
      key: "verbosity",
      label: "Verbosity",
      type: "enum",
      enumValues: ["high", "low"],
      file: "settings.json",
      prismTouch: "none",
    },
    {
      key: "runningLightSpeed",
      label: "Running-light animation speed",
      type: "enum",
      enumValues: ["fast", "medium", "slow", "off"],
      file: "settings.json",
      prismTouch: "none",
    },
    {
      key: "mcpServers",
      label: "MCP servers map",
      type: "object",
      file: "~/.gemini/config/mcp_config.json",
      prismTouch: "none",
      description:
        "mcpServers.{id}: {command,args,env} stdio or {serverUrl} SSE; plugins may ship plugins/<name>/mcp_config.json",
    },
  ],
  refresh: {
    lastResearched: "2026-08-11",
    procedure: [
      "Run `agy --help` and `agy --version`; note print/sandbox/model/conversation flags",
      "Read ~/.gemini/antigravity-cli/settings.json top-level keys (redact tokens)",
      "Read ~/.gemini/config/mcp_config.json for mcpServers shape",
      "Diff public settings table: https://antigravity.google/docs/cli/reference",
      "List plugins/prism-generated-* under ~/.gemini/antigravity-cli/plugins (and ~/.gemini/config/plugins if mirrored)",
      "Confirm Prism lowerer still emits plugins/prism-generated-<plugin>/{plugin.json,agents/,skills/,rules/,hooks.json} only — no settings.json patch",
      "Update fields[] and lastResearched",
    ],
    sources: [
      "agy --help",
      "agy --version",
      "~/.gemini/antigravity-cli/settings.json",
      "~/.gemini/config/mcp_config.json",
      "https://antigravity.google/docs/cli/reference",
      "https://antigravity.google/docs/cli/sandbox",
      "https://antigravity.google/docs/hooks",
      "https://antigravity.google/docs/plugins",
      "https://antigravity.google/docs/mcp",
      "src/harnesses.ts",
      "src/lowerer-capabilities.ts",
      "src/compile/lowerers/antigravity-cli.ts",
      "src/workflow-antigravity-worker.ts",
      "src/workflow-harness-detection.ts",
      "builtin skill agy-customizations (local install)",
    ],
  },
  notes: [
    "Binary is `agy` (not antigravity). Workflow override: PRISM_WORKFLOW_ANTIGRAVITY_BIN; related Prism-only env: PRISM_WORKFLOW_ANTIGRAVITY_PTY, _PTY_PYTHON, _PROCESS_TIMEOUT_MS, _RETRY_*.",
    "Prism global compile root is ~/.gemini/antigravity-cli/ (HARNESSES entry). Customization discovery also walks ~/.gemini/config/ and project .agents/ (or .agent/, _agents/, _agent/).",
    "Prism owns whole-file plugin bundles at plugins/prism-generated-<plugin>/ (plugin.json, agents/, skills/, rules/context.md, hooks.json + hooks/*.mjs). Lowerer returns regions: [] — no settings.json region patch.",
    "Rules are compile-managed into the plugin bundle (rules/context.md), not direct root rules files. Commands are unsupported as direct files; model commands as skills/orbits.",
    "Canonical tools lower to <PRISM_HOME>/runtime/tools/<plugin>/ (CLI invoke + skill inject), not into mcp_config.json.",
    "Official settings table omits live-observed keys model and trustedWorkspaces — keep both until docs catch up.",
    "Project-specific settings under ~/.gemini/config/projects/ can override global settings.json (CHANGELOG 1.0.12).",
    "Parent ~/.gemini/ holds oauth_creds.json, settings.json (auth), trustedFolders.json, projects.json — out of Prism ownership; never adopt.",
    "Hook native events: PreToolUse, PostToolUse, PreInvocation, PostInvocation, Stop. Prism maps tool.before/after, session.start, session.end, stop; does not expose PostInvocation/injectSteps/terminationBehavior as compile-language outputs.",
    "Workflow worker requires --print, --print-timeout, --model, --add-dir, --sandbox, --dangerously-skip-permissions, optional --conversation/--log-file; bans --continue/-c.",
  ],
};
