import type { HarnessCatalog } from "./types.js";

/** Codex CLI settings catalogue — researched 2026-08-11 from live ~/.codex + lowerer + config skill. */
export const codexCliCatalog: HarnessCatalog = {
  harness: "codex-cli",
  displayName: "Codex CLI",
  binaryNames: ["codex"],
  binaryEnvVars: ["PRISM_WORKFLOW_CODEX_BIN", "CODEX_HOME"],
  globalRoot: "~/.codex/",
  projectRoot: ".codex/",
  settingsFiles: [
    {
      path: "config.toml",
      format: "toml",
      primary: true,
      note: "User-shared; Prism only fenced marker regions (hooks + features.hooks)",
    },
    {
      path: "AGENTS.md",
      format: "md",
      note: "Rules / instructions; Prism marker regions (codex.rules.<plugin>)",
    },
    {
      path: "hooks.json",
      format: "json",
      note: "Alternate hooks representation; prefer one of hooks.json vs inline [hooks]",
    },
    {
      path: "auth.json",
      format: "json",
      note: "secrets (tokens) — never display",
    },
    {
      path: "version.json",
      format: "json",
      note: "Client version check metadata",
    },
  ],
  scanDirs: ["agents", "prompts", "skills", "hooks", "mcp", "plugins", "rules"],
  prismNamespaceMarkers: ["prism-generated-", "prism_generated_", "prism:"],
  fields: [
    {
      key: "model",
      label: "Model",
      type: "string",
      file: "config.toml",
      prismTouch: "none",
      cousin: "modelspace",
      description: "Default model slug (e.g. gpt-5.6-sol, gpt-5.6-terra)",
    },
    {
      key: "model_provider",
      label: "Model provider",
      type: "string",
      file: "config.toml",
      prismTouch: "none",
      cousin: "modelspace",
      description: "Provider id; default openai. Reserved: openai, ollama, lmstudio",
    },
    {
      key: "model_reasoning_effort",
      label: "Reasoning effort",
      type: "enum",
      enumValues: ["minimal", "low", "medium", "high", "xhigh", "max"],
      file: "config.toml",
      prismTouch: "none",
      cousin: "effort",
      description: "Also settable on agents/*.toml; workflow maps variant → this key",
    },
    {
      key: "model_verbosity",
      label: "Model verbosity",
      type: "enum",
      enumValues: ["low", "medium", "high"],
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "model_reasoning_summary",
      label: "Reasoning summary",
      type: "enum",
      enumValues: ["auto", "concise", "detailed", "none"],
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "service_tier",
      label: "Service tier",
      type: "string",
      file: "config.toml",
      prismTouch: "none",
      description: "Preferred tier for new turns (docs: flex | fast; live also uses default)",
    },
    {
      key: "approval_policy",
      label: "Approval policy",
      type: "enum",
      enumValues: ["untrusted", "on-request", "never"],
      file: "config.toml",
      prismTouch: "none",
      cousin: "permission-posture",
      description: "When Codex pauses for approval; may also be a granular table",
    },
    {
      key: "default_permissions",
      label: "Default permissions profile",
      type: "string",
      file: "config.toml",
      prismTouch: "none",
      cousin: "permission-posture",
      description:
        "Built-ins :read-only | :workspace | :danger-full-access, or custom name. Do not combine with sandbox_mode",
    },
    {
      key: "sandbox_mode",
      label: "Sandbox mode",
      type: "enum",
      enumValues: ["read-only", "workspace-write", "danger-full-access"],
      file: "config.toml",
      prismTouch: "none",
      cousin: "permission-posture",
      description: "Classic sandbox surface; mutually exclusive with default_permissions",
    },
    {
      key: "sandbox_workspace_write",
      label: "Workspace-write sandbox options",
      type: "object",
      file: "config.toml",
      prismTouch: "none",
      description: "network_access, writable_roots, exclude_tmpdir_env_var, exclude_slash_tmp",
    },
    {
      key: "permissions",
      label: "Named permission profiles",
      type: "object",
      file: "config.toml",
      prismTouch: "none",
      description: "permissions.<name>.filesystem / .network tables",
    },
    {
      key: "profile",
      label: "Active profile",
      type: "string",
      file: "config.toml",
      prismTouch: "none",
      description: "Selects [profiles.<name>] block; CLI --profile overrides",
    },
    {
      key: "profiles",
      label: "Named profiles",
      type: "object",
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "features",
      label: "Feature flags",
      type: "object",
      file: "config.toml",
      prismTouch: "region",
      description:
        "Prism may fence features.hooks = true when installing hooks (regionKey codex.features.hooks). Live keys include js_repl; docs also list codex_hooks, multi_agent, shell_snapshot, undo, memories",
    },
    {
      key: "features.hooks",
      label: "Enable hooks (Prism)",
      type: "boolean",
      file: "config.toml",
      prismTouch: "region",
      description: "Prism-owned fenced scalar under [features] when hooks are compiled",
    },
    {
      key: "hooks",
      label: "Inline hooks",
      type: "object",
      file: "config.toml",
      prismTouch: "region",
      description:
        "Prism writes [[hooks.<Event>]] array tables + command wrappers under hooks/*.mjs (regionKey codex.hooks.<plugin>)",
    },
    {
      key: "mcp_servers",
      label: "MCP servers",
      type: "object",
      file: "config.toml",
      prismTouch: "none",
      description: "mcp_servers.<id>.{command,args,cwd,env,url,enabled,startup_timeout_sec,...}",
    },
    {
      key: "plugins",
      label: "Plugins enable map",
      type: "object",
      file: "config.toml",
      prismTouch: "none",
      description: 'plugins."<name>@marketplace".enabled',
    },
    {
      key: "marketplaces",
      label: "Plugin marketplaces",
      type: "object",
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "projects",
      label: "Project trust map",
      type: "object",
      file: "config.toml",
      prismTouch: "none",
      description: 'projects."<abs-path>".trust_level — project .codex/ loads only when trusted',
    },
    {
      key: "shell_environment_policy",
      label: "Shell environment policy",
      type: "object",
      file: "config.toml",
      prismTouch: "none",
      description: "inherit / include_only / exclude / set — secrets hygiene for shell tool",
    },
    {
      key: "agents",
      label: "Subagent concurrency",
      type: "object",
      file: "config.toml",
      prismTouch: "none",
      description: "agents.max_threads, max_depth, job_max_runtime_seconds",
    },
    {
      key: "web_search",
      label: "Web search mode",
      type: "enum",
      enumValues: ["cached", "live", "disabled"],
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "notify",
      label: "Notify command",
      type: "array",
      file: "config.toml",
      prismTouch: "none",
      description: "Command argv invoked on events (e.g. turn-ended)",
    },
    {
      key: "desktop",
      label: "Desktop / app UI",
      type: "object",
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "tui",
      label: "TUI settings",
      type: "object",
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "notice",
      label: "Notice dismissals",
      type: "object",
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "openai_base_url",
      label: "OpenAI base URL",
      type: "string",
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "model_providers",
      label: "Custom model providers",
      type: "object",
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "skills.config",
      label: "Per-skill enable/disable",
      type: "array",
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "history.persistence",
      label: "History persistence",
      type: "enum",
      enumValues: ["save-all", "none"],
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "analytics.enabled",
      label: "Analytics",
      type: "boolean",
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "cli_auth_credentials_store",
      label: "CLI credentials store",
      type: "enum",
      enumValues: ["file", "keyring", "auto"],
      file: "config.toml",
      prismTouch: "none",
    },
  ],
  refresh: {
    lastResearched: "2026-08-11",
    procedure: [
      "Run `codex --help` and `codex exec --help` (timeout ok); note --config, --profile, --sandbox, --model",
      "Read ~/.codex/config.toml top-level keys and tables (redact auth/tokens/env secrets)",
      "Confirm Prism regions: AGENTS.md prism:codex.rules.* and config.toml prism:codex.hooks.* / codex.features.hooks",
      "List agents/*.toml, prompts/, skills/, hooks/ for inventory layout",
      "Cross-check https://developers.openai.com/codex/config-reference and hooks docs",
      "Diff against src/compile/lowerers/codex-cli.ts region keys and CODEX_MODEL_KEYS",
      "Update fields[] and lastResearched",
    ],
    sources: [
      "codex --help",
      "codex exec --help",
      "~/.codex/config.toml",
      "~/.codex/AGENTS.md",
      "~/.codex/hooks.json",
      "~/.codex/agents/*.toml",
      "https://developers.openai.com/codex/config-basic",
      "https://developers.openai.com/codex/config-advanced",
      "https://developers.openai.com/codex/config-reference",
      "https://developers.openai.com/codex/hooks",
      "src/harnesses.ts",
      "src/lowerer-capabilities.ts",
      "src/compile/lowerers/codex-cli.ts",
      "src/workflow-codex-worker.ts",
      "skills/codex-configuration (if installed)",
    ],
  },
  notes: [
    "Prism does not whole-file own config.toml; only fenced regions for hooks and features.hooks.",
    "Rules install as marker regions in AGENTS.md (regionKey codex.rules.<plugin>); also file-router fences.",
    "Agents lower to agents/<name>.toml (name, description, developer_instructions, model keys).",
    "Commands install as prompts/*.md; skills and orbits as skills/<name>/SKILL.md.",
    "Canonical tools → <PRISM_HOME>/runtime/tools/<plugin>/; invoke via `prism tools invoke`.",
    "No plugin-bundle surface — direct files + config patches only (lowerer-capabilities).",
    "Workflow worker: PRISM_WORKFLOW_CODEX_BIN, `codex exec`, maps sandbox modes and model_reasoning_effort via --config.",
    "Project .codex/ layers load only for trusted projects (projects.<path>.trust_level).",
    "Do not combine default_permissions with sandbox_mode / sandbox_workspace_write.",
    "auth.json holds ChatGPT/OAuth tokens — always redacted in TUI.",
  ],
};
