import type { HarnessCatalog } from "./types.js";

/** Cursor Agent CLI settings catalogue — researched 2026-09-09 from live `agent` 2026.09.08-6caf4ff, ~/.cursor/cli-config.json, and official CLI docs. */
export const cursorCatalog: HarnessCatalog = {
  harness: "cursor",
  displayName: "Cursor",
  binaryNames: ["agent", "cursor-agent", "cursor"],
  binaryEnvVars: ["PRISM_WORKFLOW_CURSOR_BIN"],
  globalRoot: "~/.cursor/",
  projectRoot: ".cursor/",
  settingsFiles: [
    { path: "cli-config.json", format: "json", primary: true, note: "Agent CLI settings" },
    {
      path: "mcp.json",
      format: "json",
      note: "MCP server map; Prism does not patch",
    },
    {
      path: "hooks.json",
      format: "json",
      note: "Native CLI/IDE hooks; Prism hooks unsupported for Cursor",
    },
    {
      path: "auth.json",
      format: "json",
      note: "secrets — accessToken/refreshToken — never display",
    },
    {
      path: ".cursorrules",
      format: "md",
      note: "Legacy rules file; Prism may marker-region inject tools-cli",
    },
    {
      path: "rules/",
      format: "mdc",
      note: "Project/global .mdc rules dir; Prism install writes owned .mdc files",
    },
    {
      path: "cli.json",
      format: "json",
      note: "Project-layer CLI overrides (permissions only). Relative to harness root: <project>/.cursor/cli.json",
    },
    {
      path: "sandbox.json",
      format: "json",
      note: "Optional sandbox policy; project file wins over ~/.cursor/sandbox.json",
    },
  ],
  scanDirs: ["skills", "plugins", "commands", "rules", "plugins/local"],
  prismNamespaceMarkers: ["prism-generated-"],
  fields: [
    {
      key: "version",
      label: "CLI config schema version",
      type: "number",
      file: "cli-config.json",
      prismTouch: "none",
      description: "Required; current schema is 1. CLI-managed.",
    },
    {
      key: "permissions.allow",
      label: "Permission allow list",
      type: "array",
      file: "cli-config.json",
      prismTouch: "none",
      cousin: "permission-posture",
      description: 'Patterns e.g. "Shell(**)", "Mcp(server, tool)"',
    },
    {
      key: "permissions.deny",
      label: "Permission deny list",
      type: "array",
      file: "cli-config.json",
      prismTouch: "none",
      cousin: "permission-posture",
    },
    {
      key: "editor.vimMode",
      label: "Vim mode",
      type: "boolean",
      file: "cli-config.json",
      prismTouch: "none",
    },
    {
      key: "editor.defaultBehavior",
      label: "Default editor behavior",
      type: "enum",
      enumValues: ["ide", "agent"],
      file: "cli-config.json",
      prismTouch: "none",
      description: "Documented by update-cli-config skill; may be absent on disk",
    },
    {
      key: "channel",
      label: "Release channel",
      type: "enum",
      enumValues: ["prod", "lab", "static"],
      file: "cli-config.json",
      prismTouch: "none",
    },
    {
      key: "model",
      label: "Selected model object",
      type: "object",
      file: "cli-config.json",
      prismTouch: "none",
      cousin: "modelspace",
      description: "CLI-managed via /model; fields include modelId, displayName, maxMode",
    },
    {
      key: "model.modelId",
      label: "Model id",
      type: "string",
      file: "cli-config.json",
      prismTouch: "none",
      cousin: "modelspace",
    },
    {
      key: "selectedModel",
      label: "Selected model + parameters",
      type: "object",
      file: "cli-config.json",
      prismTouch: "none",
      cousin: "modelspace",
      description: "Live shape: { modelId, parameters: [{ id, value }] }",
    },
    {
      key: "modelParameters",
      label: "Per-model parameters",
      type: "object",
      file: "cli-config.json",
      prismTouch: "none",
      cousin: "effort",
      description: "Live map modelId → [{ id: effort|fast, value }]",
    },
    {
      key: "modelSelectionHistory",
      label: "Model selection history",
      type: "array",
      file: "cli-config.json",
      prismTouch: "none",
      description: "CLI-managed picker history — do not edit",
    },
    {
      key: "maxMode",
      label: "Max mode",
      type: "boolean",
      file: "cli-config.json",
      prismTouch: "none",
    },
    {
      key: "hasChangedDefaultModel",
      label: "User changed default model",
      type: "boolean",
      file: "cli-config.json",
      prismTouch: "none",
      description: "CLI-managed flag",
    },
    {
      key: "approvalMode",
      label: "Approval mode",
      type: "enum",
      enumValues: ["allowlist", "auto-review", "unrestricted"],
      file: "cli-config.json",
      prismTouch: "none",
      cousin: "permission-posture",
    },
    {
      key: "sandbox.mode",
      label: "Sandbox mode",
      type: "enum",
      enumValues: ["disabled", "enabled"],
      file: "cli-config.json",
      prismTouch: "none",
    },
    {
      key: "sandbox.networkAccess",
      label: "Sandbox network access",
      type: "enum",
      enumValues: ["user_config_only", "user_config_with_defaults", "allow_all"],
      file: "cli-config.json",
      prismTouch: "none",
    },
    {
      key: "sandbox.networkAllowlist",
      label: "Sandbox network allowlist",
      type: "array",
      file: "cli-config.json",
      prismTouch: "none",
      description: "Optional; documented by update-cli-config skill",
    },
    {
      key: "network.useHttp1ForAgent",
      label: "HTTP/1.1 for agent",
      type: "boolean",
      file: "cli-config.json",
      prismTouch: "none",
      description: "Proxy-friendly SSE fallback when HTTP/2 fails",
    },
    {
      key: "display.mode",
      label: "Display mode",
      type: "string",
      file: "cli-config.json",
      prismTouch: "none",
      description: "Present on live disk; not in the public schema table",
    },
    {
      key: "display.showLineNumbers",
      label: "Show line numbers",
      type: "boolean",
      file: "cli-config.json",
      prismTouch: "none",
    },
    {
      key: "display.showThinkingBlocks",
      label: "Show thinking blocks",
      type: "boolean",
      file: "cli-config.json",
      prismTouch: "none",
    },
    {
      key: "display.showStatusIndicators",
      label: "Status indicators",
      type: "boolean",
      file: "cli-config.json",
      prismTouch: "none",
    },
    {
      key: "display.showStatusLineRunningTime",
      label: "Status line running time",
      type: "boolean",
      file: "cli-config.json",
      prismTouch: "none",
    },
    {
      key: "notifications",
      label: "Terminal notifications",
      type: "boolean",
      file: "cli-config.json",
      prismTouch: "none",
    },
    {
      key: "hints",
      label: "CLI hints",
      type: "boolean",
      file: "cli-config.json",
      prismTouch: "none",
    },
    {
      key: "rewind",
      label: "Rewind sessions",
      type: "boolean",
      file: "cli-config.json",
      prismTouch: "none",
    },
    {
      key: "suggestNextPrompt",
      label: "Suggest next prompt",
      type: "boolean",
      file: "cli-config.json",
      prismTouch: "none",
      description: "Official docs field; may be absent on disk",
    },
    {
      key: "modelSlashCommands",
      label: "Model slash commands",
      type: "boolean",
      file: "cli-config.json",
      prismTouch: "none",
      description: "Present on live disk; not in public schema table",
    },
    {
      key: "exploreSubagentModel",
      label: "Explore subagent model (legacy)",
      type: "enum",
      enumValues: ["default", "inherit"],
      file: "cli-config.json",
      prismTouch: "none",
      description: "Legacy Explore model. subagentModels.explore wins when both are set.",
    },
    {
      key: "subagentModels",
      label: "Per-subagent model settings",
      type: "object",
      file: "cli-config.json",
      prismTouch: "none",
      description: "Optional; explore: default|inherit|disabled or { modelId, parameters?, maxMode? }",
    },
    {
      key: "autoAcceptWebSearch",
      label: "Auto-accept web search",
      type: "boolean",
      file: "cli-config.json",
      prismTouch: "none",
    },
    {
      key: "showSandboxIntro",
      label: "Show sandbox intro",
      type: "boolean",
      file: "cli-config.json",
      prismTouch: "none",
      description: "One-time UI flag — do not edit",
    },
    {
      key: "attribution.attributeCommitsToAgent",
      label: "Attribute commits to agent",
      type: "boolean",
      file: "cli-config.json",
      prismTouch: "none",
    },
    {
      key: "attribution.attributePRsToAgent",
      label: "Attribute PRs to agent",
      type: "boolean",
      file: "cli-config.json",
      prismTouch: "none",
    },
    {
      key: "webFetchDomainAllowlist",
      label: "Web fetch domain allowlist",
      type: "array",
      file: "cli-config.json",
      prismTouch: "none",
      description: "Optional skill-documented field",
    },
    {
      key: "bedrock",
      label: "AWS Bedrock integration",
      type: "object",
      file: "cli-config.json",
      prismTouch: "none",
      description: "Optional skill-documented block (enabled, mode, region, …)",
    },
    {
      key: "authInfo",
      label: "Cached auth identity",
      type: "object",
      file: "cli-config.json",
      prismTouch: "none",
      description: "CLI cache (email/userId); not for manual edit",
    },
    {
      key: "privacyCache",
      label: "Privacy cache",
      type: "object",
      file: "cli-config.json",
      prismTouch: "none",
      description: "Internal cache — do not edit",
    },
    {
      key: "mcpServers",
      label: "MCP servers",
      type: "object",
      file: "mcp.json",
      prismTouch: "none",
      description: "User MCP map. Prism tools are CLI-only; no mcp.json patch.",
    },
    {
      key: "hooks",
      label: "Native hooks map",
      type: "object",
      file: "hooks.json",
      prismTouch: "none",
      description: "Cursor native hooks. Prism hook DSL unsupported for this harness.",
    },
  ],
  refresh: {
    lastResearched: "2026-09-09",
    procedure: [
      "Run `agent about --format json` and `agent --help` if on PATH (timeout ok)",
      "Read ~/.cursor/cli-config.json top-level keys (redact authInfo/tokens)",
      "Read ~/.cursor/mcp.json, hooks.json, and sandbox.json if present",
      "Compare https://cursor.com/docs/cli/reference/configuration and https://cursor.com/docs/cli/reference/parameters",
      "List ~/.cursor/plugins/local/prism-generated-* and ~/.cursor/skills/",
      "Re-check src/harnesses.ts, src/lowerer-capabilities.ts, src/compile/lowerers/cursor.ts, src/refresh.ts, src/workflow-cursor-worker.ts, src/workflow-harness-detection.ts",
      "Update fields[] and lastResearched",
    ],
    sources: [
      "https://cursor.com/docs/cli/reference/configuration",
      "https://cursor.com/docs/cli/reference/parameters",
      "https://cursor.com/docs/cli/reference/output-format",
      "https://cursor.com/docs/cli/headless",
      "https://cursor.com/docs/cli/overview",
      "agent --help / agent about --format json",
      "~/.cursor/cli-config.json",
      "~/.cursor/mcp.json",
      "~/.cursor/hooks.json",
      "~/.cursor/skills-cursor/update-cli-config/SKILL.md",
      "src/harnesses.ts",
      "src/lowerer-capabilities.ts",
      "src/compile/lowerers/cursor.ts",
      "src/refresh.ts",
      "src/workflow-cursor-worker.ts",
      "src/workflow-harness-detection.ts",
    ],
  },
  notes: [
    "Primary settings surface is Agent CLI `cli-config.json`, not VS Code User/settings.json. IDE Cursor settings live under Application Support when the IDE is installed.",
    "Project overrides: only permissions via `.cursor/cli.json` (walk git-root → cwd). Catalog path is `cli.json` relative to the harness root so project inventory resolves `<project>/.cursor/cli.json`.",
    "CURSOR_CONFIG_DIR overrides the config directory; XDG_CONFIG_HOME uses $XDG_CONFIG_HOME/cursor/cli-config.json on Linux/BSD. Those are config-dir overrides, not binary paths. Binary override is PRISM_WORKFLOW_CURSOR_BIN.",
    "Prism does not whole-file own cli-config.json or mcp.json. Commands install under plugins/local/prism-generated-<plugin>/.cursor-plugin/plugin.json + commands/.",
    "Skills install direct to skills/. Rules install as owned .mdc under rules/ (or project .cursor/rules/); .cursorrules may receive marker regions for tools-cli inject.",
    "Compile: tools-only (CLI runtime under PRISM_HOME). Agents, orbits, hooks, skill permissions unsupported. workflowWorker: true via `agent --print --output-format stream-json`.",
    "Do not hand-edit model/selectedModel/hasChangedDefaultModel/privacyCache/authInfo/showSandboxIntro caches — CLI-managed.",
    "Internal CLI caches (autoReviewAvailabilityCache, serverConfigCache, runEverythingSettingsPromptStreak) are omitted from fields[].",
    "Legacy ~/.cursor/commands/*.md may still exist from pre-plugin-bundle installs; Prism now writes plugins/local only.",
  ],
};
