import type { HarnessCatalog } from "./types.js";

/** Devin CLI settings catalogue — researched 2026-08-11 from live config.json + lowerer/worker. */
export const devinCatalog: HarnessCatalog = {
  harness: "devin",
  displayName: "Devin CLI",
  binaryNames: ["devin"],
  binaryEnvVars: ["PRISM_WORKFLOW_DEVIN_BIN"],
  globalRoot: "~/.config/devin/",
  projectRoot: ".devin/",
  settingsFiles: [
    {
      path: "config.json",
      format: "json",
      primary: true,
      note: "User prefs + herdr hooks; never whole-file adopt",
    },
    {
      path: "AGENTS.md",
      format: "md",
      note: "Rules; Prism HTML marker regions",
    },
    {
      path: "hooks.v1.json",
      format: "json",
      note: "Project-scope Claude-compatible hooks load path; global uses config.json#hooks",
    },
  ],
  scanDirs: ["skills", "hooks", "cli"],
  prismNamespaceMarkers: ["prism-generated-"],
  fields: [
    {
      key: "version",
      label: "Config schema version",
      type: "number",
      file: "config.json",
      prismTouch: "none",
      description: "Live value observed as 1",
    },
    {
      key: "agent.model",
      label: "Default model",
      type: "string",
      file: "config.json",
      prismTouch: "none",
      cousin: "modelspace",
      description: "Workflow default swe-1-7; CLI --model overrides per run",
    },
    {
      key: "theme_mode",
      label: "Theme mode",
      type: "enum",
      enumValues: ["dark", "light"],
      file: "config.json",
      prismTouch: "none",
    },
    {
      key: "shell.setup_complete",
      label: "Shell setup complete",
      type: "boolean",
      file: "config.json",
      prismTouch: "none",
    },
    {
      key: "devin.org_id",
      label: "Organization ID",
      type: "secret",
      file: "config.json",
      prismTouch: "none",
      description: "Cognition org binding — never display raw",
    },
    {
      key: "hooks",
      label: "Native hooks map",
      type: "object",
      file: "config.json",
      prismTouch: "region",
      description:
        "Global: Prism upserts json-array-member entries under hooks.<NativeEvent> without whole-file adopt. Foreign entries (e.g. herdr) stay. Events: PreToolUse, PostToolUse, UserPromptSubmit, PermissionRequest, SessionStart, SessionEnd, Stop, PostCompaction",
    },
    {
      key: "hooks.SessionStart",
      label: "SessionStart hooks",
      type: "array",
      file: "config.json",
      prismTouch: "region",
      description: "Array of { matcher?, hooks: [{ type: command, command, timeout }] }",
    },
    {
      key: "hooks.PreToolUse",
      label: "PreToolUse hooks",
      type: "array",
      file: "config.json",
      prismTouch: "region",
      description: "Block via exit code 2 from wrapper",
    },
    {
      key: "hooks.PostToolUse",
      label: "PostToolUse hooks",
      type: "array",
      file: "config.json",
      prismTouch: "region",
    },
    {
      key: "hooks.UserPromptSubmit",
      label: "UserPromptSubmit hooks",
      type: "array",
      file: "config.json",
      prismTouch: "region",
    },
    {
      key: "hooks.PermissionRequest",
      label: "PermissionRequest hooks",
      type: "array",
      file: "config.json",
      prismTouch: "region",
      description: "Decision approve | block",
    },
    {
      key: "hooks.Stop",
      label: "Stop hooks",
      type: "array",
      file: "config.json",
      prismTouch: "region",
    },
    {
      key: "hooks.SessionEnd",
      label: "SessionEnd hooks",
      type: "array",
      file: "config.json",
      prismTouch: "region",
    },
    {
      key: "hooks.PostCompaction",
      label: "PostCompaction hooks",
      type: "array",
      file: "config.json",
      prismTouch: "region",
      description: "Mapped from Prism compact.after; may be absent until first install",
    },
    {
      key: "permission-mode",
      label: "CLI permission mode",
      type: "enum",
      enumValues: ["auto", "accept-edits", "smart", "dangerous"],
      file: "config.json",
      prismTouch: "none",
      cousin: "permission-posture",
      description:
        "Not a durable config key in live file; workflow passes --permission-mode (auto|accept-edits|dangerous from Prism restricted|permissive|full-access)",
    },
  ],
  refresh: {
    lastResearched: "2026-08-11",
    procedure: [
      "Run `devin --help` / `devin help` and note -p, --model, --permission-mode, -r, --agent-config, --export, plugins, auth",
      "Read ~/.config/devin/config.json top-level keys (redact devin.org_id and any tokens)",
      "List hooks event names under config.json#hooks and any herdr vs prism-generated command paths",
      "Confirm AGENTS.md prism:file-router marker regions; project rules target repo AGENTS.md",
      "Check project .devin/hooks.v1.json vs global hooks/prism-generated-*.hooks.v1.json inventory",
      "Cross-check src/compile/lowerers/devin.ts and workflow-devin-worker.ts defaults",
      "Update fields[] and lastResearched",
    ],
    sources: [
      "devin --help",
      "devin version",
      "~/.config/devin/config.json",
      "~/.config/devin/AGENTS.md",
      "~/.config/devin/hooks/",
      "src/harnesses.ts",
      "src/lowerer-capabilities.ts",
      "src/compile/lowerers/devin.ts",
      "src/workflow-devin-worker.ts",
      "src/workflow-harness-detection.ts",
      "docs/lowerer-capability-matrix.md",
      "AGENTS.md (Devin CLI paragraph)",
    ],
  },
  notes: [
    "Never whole-file own config.json — herdr hooks and user prefs share it; global Prism hooks are json-array-member regions only.",
    "Project scope: hooks load from .devin/hooks.v1.json (Prism may whole-file own that path per plugin claim). Global: config.json#hooks + wrappers under hooks/prism-generated-<plugin>/*.mjs.",
    "Install skills → ~/.config/devin/skills/ or project .devin/skills/; compile orbits lower as skills. No agents/commands/tools/plugins in PR1.",
    "Rules: global markers in ~/.config/devin/AGENTS.md; project markers on repo-root AGENTS.md (not under .devin/). Also discovers AGENT.md, CLAUDE.md, AGENTS.local.md.",
    "Workflow: `devin -p` + --model (default swe-1-7) + --permission-mode + optional --agent-config (ephemeral YAML system_instructions) + --export ATIF + -r resume. Auth via `devin auth login`.",
    "Plugins are beta (`devin plugins install`); Prism does not manage them.",
    "cli/ dir present under global root on disk — inventory only; not a Prism write surface.",
  ],
};
