import type { HarnessCatalog } from "./types.js";

/**
 * Factory Droid settings catalogue — researched 2026-08-11 from
 * docs.factory.ai/droid-cli/settings, live ~/.factory layout, harness registry,
 * and src/compile/lowerers/factory-droid.ts.
 *
 * Note: ~/.factory/settings.json was absent on the research machine (created on
 * first `droid` run). Keys below come from official settings reference + mcp.json
 * on disk + Prism lowerer surfaces.
 */
export const factoryDroidCatalog: HarnessCatalog = {
  harness: "factory-droid",
  displayName: "Factory Droid",
  binaryNames: ["droid"],
  globalRoot: "~/.factory/",
  projectRoot: ".factory/",
  settingsFiles: [
    {
      path: "settings.json",
      format: "json",
      primary: true,
      note: "Personal CLI config; created with defaults on first droid run",
    },
    {
      path: "settings.local.json",
      format: "json",
      note: "Local override merged on top of settings.json (user or project)",
    },
    {
      path: "mcp.json",
      format: "json",
      note: "MCP servers; user/project/folder layers — Prism does not patch",
    },
    {
      path: "AGENTS.md",
      format: "md",
      note: "Rules; Prism marker regions (<!-- BEGIN/END --> and prism:file-router fences)",
    },
    {
      path: "host.json",
      format: "json",
      note: "Runtime host identity (hostId) — not user prefs",
    },
    {
      path: "background-processes.json",
      format: "json",
      note: "Runtime process ledger",
    },
    {
      path: "background-tasks.json",
      format: "json",
      note: "Runtime task ledger",
    },
  ],
  scanDirs: ["plugins", "skills", "commands", "droids"],
  prismNamespaceMarkers: ["prism-generated-"],
  fields: [
    // ── Primary settings.json (personal / project) ──────────────────────────
    {
      key: "model",
      label: "Default model",
      type: "string",
      file: "settings.json",
      prismTouch: "none",
      cousin: "modelspace",
      description: "Factory-managed or public model ID; product default when unset",
    },
    {
      key: "reasoningEffort",
      label: "Reasoning effort",
      type: "enum",
      enumValues: [
        "none",
        "dynamic",
        "off",
        "minimal",
        "low",
        "medium",
        "high",
        "xhigh",
        "max",
      ],
      file: "settings.json",
      prismTouch: "none",
      cousin: "effort",
      description: "Model-dependent subset; see docs.factory.ai models table",
    },
    {
      key: "sessionDefaultSettings.interactionMode",
      label: "Default interaction mode",
      type: "enum",
      enumValues: ["auto", "spec"],
      file: "settings.json",
      prismTouch: "none",
    },
    {
      key: "sessionDefaultSettings.autonomyLevel",
      label: "Default autonomy level",
      type: "enum",
      enumValues: ["off", "low", "medium", "high"],
      file: "settings.json",
      prismTouch: "none",
      cousin: "permission-posture",
    },
    {
      key: "sessionDefaultSettings.specModeModel",
      label: "Spec mode model",
      type: "string",
      file: "settings.json",
      prismTouch: "none",
    },
    {
      key: "sessionDefaultSettings.specModeReasoningEffort",
      label: "Spec mode reasoning effort",
      type: "string",
      file: "settings.json",
      prismTouch: "none",
    },
    {
      key: "cloudSessionSync",
      label: "Cloud session sync",
      type: "boolean",
      file: "settings.json",
      prismTouch: "none",
    },
    {
      key: "diffMode",
      label: "Diff mode",
      type: "enum",
      enumValues: ["github", "unified"],
      file: "settings.json",
      prismTouch: "none",
    },
    {
      key: "completionSound",
      label: "Completion sound",
      type: "string",
      file: "settings.json",
      prismTouch: "none",
      description: "off | bell | fx-ok01 | fx-ack01 | custom path",
    },
    {
      key: "awaitingInputSound",
      label: "Awaiting-input sound",
      type: "string",
      file: "settings.json",
      prismTouch: "none",
    },
    {
      key: "soundFocusMode",
      label: "Sound focus mode",
      type: "enum",
      enumValues: ["always", "focused", "unfocused"],
      file: "settings.json",
      prismTouch: "none",
    },
    {
      key: "subagentSounds",
      label: "Subagent sounds",
      type: "enum",
      enumValues: ["on", "off"],
      file: "settings.json",
      prismTouch: "none",
    },
    {
      key: "commandAllowlist",
      label: "Command allowlist",
      type: "array",
      file: "settings.json",
      prismTouch: "none",
    },
    {
      key: "commandDenylist",
      label: "Command denylist",
      type: "array",
      file: "settings.json",
      prismTouch: "none",
    },
    {
      key: "commandBlocklist",
      label: "Command blocklist",
      type: "array",
      file: "settings.json",
      prismTouch: "none",
      description: "Hard stop even under full autonomy / skip-permissions",
    },
    {
      key: "includeCoAuthoredByDroid",
      label: "Co-authored-by Droid trailer",
      type: "boolean",
      file: "settings.json",
      prismTouch: "none",
    },
    {
      key: "enableDroidShield",
      label: "Droid Shield",
      type: "boolean",
      file: "settings.json",
      prismTouch: "none",
      description: "Secret scanning and git guardrails",
    },
    {
      key: "hooksDisabled",
      label: "Hooks disabled (global)",
      type: "boolean",
      file: "settings.json",
      prismTouch: "none",
      description: "Prism hooks live in plugins/prism-generated-*/hooks/, not settings.json",
    },
    {
      key: "showHookOutput",
      label: "Show hook output",
      type: "boolean",
      file: "settings.json",
      prismTouch: "none",
    },
    {
      key: "disabledSkills",
      label: "Disabled skills",
      type: "array",
      file: "settings.json",
      prismTouch: "none",
      description: "User+project arrays combined; sanitized skill names",
    },
    {
      key: "ideAutoConnect",
      label: "IDE auto-connect",
      type: "boolean",
      file: "settings.json",
      prismTouch: "none",
    },
    {
      key: "showThinkingInMainView",
      label: "Show thinking in main view",
      type: "boolean",
      file: "settings.json",
      prismTouch: "none",
    },
    {
      key: "customModels",
      label: "Custom models (BYOK)",
      type: "array",
      file: "settings.json",
      prismTouch: "none",
      description: "Array of BYOK model configs; apiKey may use ${ENV} — treat as secret",
    },
    {
      key: "blockOnMcpLoad",
      label: "Block on MCP load",
      type: "boolean",
      file: "settings.json",
      prismTouch: "none",
    },
    {
      key: "toolResultDisplay",
      label: "Tool result display",
      type: "enum",
      enumValues: ["expanded", "compact"],
      file: "settings.json",
      prismTouch: "none",
    },
    {
      key: "showTokenUsageIndicator",
      label: "Token usage indicator",
      type: "boolean",
      file: "settings.json",
      prismTouch: "none",
    },
    {
      key: "todoDisplayMode",
      label: "Todo display mode",
      type: "string",
      file: "settings.json",
      prismTouch: "none",
    },
    {
      key: "logoAnimation",
      label: "Logo animation",
      type: "enum",
      enumValues: ["once", "always", "off"],
      file: "settings.json",
      prismTouch: "none",
    },
    {
      key: "theme",
      label: "TUI theme",
      type: "string",
      file: "settings.json",
      prismTouch: "none",
    },
    {
      key: "overrideTerminalColors",
      label: "Override terminal colors",
      type: "boolean",
      file: "settings.json",
      prismTouch: "none",
    },
    {
      key: "nerdFont",
      label: "Nerd Font glyphs",
      type: "boolean",
      file: "settings.json",
      prismTouch: "none",
    },
    {
      key: "subagentAutonomyLevel",
      label: "Subagent autonomy level",
      type: "enum",
      enumValues: ["inherit", "off", "low", "medium", "high"],
      file: "settings.json",
      prismTouch: "none",
      cousin: "permission-posture",
    },
    {
      key: "subagentModelSettings.lightModel",
      label: "Subagent light model",
      type: "string",
      file: "settings.json",
      prismTouch: "none",
      cousin: "modelspace",
    },
    {
      key: "subagentModelSettings.mediumModel",
      label: "Subagent medium model",
      type: "string",
      file: "settings.json",
      prismTouch: "none",
      cousin: "modelspace",
    },
    {
      key: "subagentModelSettings.heavyModel",
      label: "Subagent heavy model",
      type: "string",
      file: "settings.json",
      prismTouch: "none",
      cousin: "modelspace",
    },
    {
      key: "missionModelSettings.workerModel",
      label: "Mission worker model",
      type: "string",
      file: "settings.json",
      prismTouch: "none",
    },
    {
      key: "missionOrchestratorModel",
      label: "Mission orchestrator model",
      type: "string",
      file: "settings.json",
      prismTouch: "none",
    },
    {
      key: "keepSystemAwakeDuringMissions",
      label: "Keep system awake during missions",
      type: "boolean",
      file: "settings.json",
      prismTouch: "none",
    },
    {
      key: "compactionTokenLimit",
      label: "Compaction token limit",
      type: "number",
      file: "settings.json",
      prismTouch: "none",
    },
    {
      key: "compactionTokenLimitPerModel",
      label: "Compaction limit per model",
      type: "object",
      file: "settings.json",
      prismTouch: "none",
    },
    {
      key: "compactionModel",
      label: "Compaction model",
      type: "string",
      file: "settings.json",
      prismTouch: "none",
    },
    {
      key: "modelFallbacks",
      label: "Model fallbacks",
      type: "object",
      file: "settings.json",
      prismTouch: "none",
    },
    {
      key: "specSaveDir",
      label: "Spec save directory",
      type: "string",
      file: "settings.json",
      prismTouch: "none",
      description: "Default ~/.factory/specs",
    },
    {
      key: "statusLine",
      label: "Status line",
      type: "object",
      file: "settings.json",
      prismTouch: "none",
      description: '{ command, padding?, maxRows? } — configure via /statusline',
    },
    {
      key: "worktreeDirectory",
      label: "Worktree directory",
      type: "string",
      file: "settings.json",
      prismTouch: "none",
      description: "Default ~/.factory/worktrees",
    },
    {
      key: "llmRequestTimeout",
      label: "LLM request timeout (ms)",
      type: "number",
      file: "settings.json",
      prismTouch: "none",
    },
    {
      key: "subagentInactivityTimeout",
      label: "Subagent inactivity timeout (ms)",
      type: "number",
      file: "settings.json",
      prismTouch: "none",
    },
    {
      key: "remoteAccessEnabled",
      label: "Remote access enabled",
      type: "boolean",
      file: "settings.json",
      prismTouch: "none",
    },
    {
      key: "enabledPlugins",
      label: "Enabled plugins",
      type: "object",
      file: "settings.json",
      prismTouch: "none",
      description:
        "Map plugin@marketplace → boolean; Prism drops plugins/prism-generated-* without patching this map",
    },
    {
      key: "extraKnownMarketplaces",
      label: "Extra known marketplaces",
      type: "object",
      file: "settings.json",
      prismTouch: "none",
      description: "Marketplace source registry for droid plugin install",
    },
    // ── Enterprise / org (document only; user TUI typically read-only) ──────
    {
      key: "maxAutonomyLevel",
      label: "Max autonomy level (org)",
      type: "enum",
      enumValues: ["off", "low", "medium", "high"],
      file: "settings.json",
      prismTouch: "none",
      description: "Enterprise clamp on session/subagent autonomy",
    },
    {
      key: "modelPolicy",
      label: "Model policy (org)",
      type: "object",
      file: "settings.json",
      prismTouch: "none",
    },
    {
      key: "mcpPolicy",
      label: "MCP policy (org)",
      type: "object",
      file: "settings.json",
      prismTouch: "none",
    },
    {
      key: "sandbox",
      label: "Sandbox (org/user)",
      type: "object",
      file: "settings.json",
      prismTouch: "none",
    },
    {
      key: "allowManagedHooksOnly",
      label: "Managed hooks only (org)",
      type: "boolean",
      file: "settings.json",
      prismTouch: "none",
    },
    {
      key: "disableAutoUpdate",
      label: "Disable auto-update (org)",
      type: "boolean",
      file: "settings.json",
      prismTouch: "none",
    },
    // ── mcp.json ────────────────────────────────────────────────────────────
    {
      key: "mcpServers",
      label: "MCP servers",
      type: "object",
      file: "mcp.json",
      prismTouch: "none",
      description:
        "Map of server name → { type, command|url, args, env, headers, disabled, … }; secrets via ${ENV}",
    },
    // ── AGENTS.md (Prism regions) ───────────────────────────────────────────
    {
      key: "AGENTS.md#region",
      label: "Rules regions",
      type: "string",
      file: "AGENTS.md",
      prismTouch: "region",
      description:
        "Prism install-phase rules + inline skills as marker regions; not whole-file ownership",
    },
  ],
  refresh: {
    lastResearched: "2026-08-11",
    procedure: [
      "Run `droid --help` and `droid exec --help` if binary on PATH",
      "Read https://docs.factory.ai/droid-cli/settings for settings.json key table",
      "Read ~/.factory/settings.json + settings.local.json if present (redact customModels.apiKey)",
      "Read ~/.factory/mcp.json top-level keys (redact env/headers secrets)",
      "List ~/.factory/plugins/prism-generated-* for compile layout (.factory-plugin/, droids/, skills/, hooks/)",
      "Confirm AGENTS.md still uses <!-- BEGIN/END --> and prism:file-router fences",
      "Diff src/harnesses.ts factory-droid entry + src/compile/lowerers/factory-droid.ts",
      "Update fields[] and lastResearched",
    ],
    sources: [
      "droid --help",
      "droid exec --help",
      "https://docs.factory.ai/droid-cli/settings",
      "https://docs.factory.ai/cli/configuration/plugins",
      "https://docs.factory.ai/cli/configuration/custom-droids",
      "https://docs.factory.ai/cli/configuration/mcp",
      "https://docs.factory.ai/reference/hooks-reference",
      "~/.factory/settings.json",
      "~/.factory/mcp.json",
      "~/.factory/AGENTS.md",
      "src/harnesses.ts",
      "src/lowerer-capabilities.ts",
      "src/compile/lowerers/factory-droid.ts",
      "src/refresh.ts (rules regions; skills bundle-when-compile)",
    ],
  },
  notes: [
    "Binary is `droid` (interactive TUI) and `droid exec` (headless). No Prism workflow worker for this harness.",
    "Prism does not whole-file own settings.json or mcp.json; rules use marker regions in AGENTS.md only.",
    "Compile emits plugins/prism-generated-<plugin>/ with .factory-plugin/plugin.json, droids/, skills/, hooks/hooks.json + wrappers. Hook events: PreToolUse/PostToolUse/SessionStart/SessionEnd.",
    "Install-phase: rules → AGENTS.md regions; commands → commands/; skills-only plugins → skills/. When compile targets agents/tools/hooks, targeted skills bundle into the plugin (avoid double-load).",
    "Direct agentsDir is droids/; compile-phase droids live inside the generated plugin, not root droids/.",
    "Droid frontmatter keys Prism lowers: name, description, model (default inherit), reasoningEffort (low|medium|high), tools (category or array). Categories: read-only, edit, execute, web, mcp.",
    "Canonical tools are CLI-only under PRISM_HOME/runtime/tools/; Prism does not emit plugin mcp.json.",
    "Legacy .droid.yaml is listed as alternativeRulesFiles but docs steer to .factory/ settings + AGENTS.md.",
    "settings.json was missing on research host until first droid run; catalogue keys from official docs + live mcp.json/AGENTS.md/plugins.",
  ],
};
