import type { HarnessCatalog } from "./types.js";

/** Grok Build settings catalogue — researched 2026-08-13 from live config.toml + ~/.grok/docs + Prism lowerer. */
export const grokCatalog: HarnessCatalog = {
  harness: "grok",
  displayName: "Grok Build",
  binaryNames: ["grok"],
  binaryEnvVars: ["PRISM_WORKFLOW_GROK_BIN", "GROK_HOME"],
  globalRoot: "~/.grok/",
  projectRoot: ".grok/",
  settingsFiles: [
    { path: "config.toml", format: "toml", primary: true },
    {
      path: "pager.toml",
      format: "toml",
      note: "TUI appearance; optional — absent on many installs",
    },
    {
      path: "AGENTS.md",
      format: "md",
      note: "Global rules; Prism marker regions (install-phase)",
    },
    {
      path: "trusted_folders.toml",
      format: "toml",
      note: "Per-folder trust decisions",
    },
    {
      path: "auth.json",
      format: "json",
      note: "secrets — never display",
    },
    {
      path: "settings.json",
      format: "json",
      note: "Optional Claude-compat surface (marketplaces / permissions); not primary",
    },
    {
      path: "memory/MEMORY.md",
      format: "md",
      note: "Global memory (relative to ~/.grok/, not project .grok/). Inventory must not treat this as a project-root scan.",
    },
  ],
  scanDirs: [
    "skills",
    "plugins",
    "agents",
    "hooks",
    "workflows",
    "installed-plugins",
    "bundled",
  ],
  prismNamespaceMarkers: ["prism-generated-"],
  fields: [
    {
      key: "models.default",
      label: "Default model",
      type: "string",
      file: "config.toml",
      prismTouch: "none",
      cousin: "modelspace",
      description: "Model for new sessions; live example: grok-composer-2.5-fast",
    },
    {
      key: "models.web_search",
      label: "Web search model",
      type: "string",
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "models.default_reasoning_effort",
      label: "Default reasoning effort",
      type: "enum",
      enumValues: ["low", "medium", "high", "xhigh"],
      file: "config.toml",
      prismTouch: "none",
      cousin: "effort",
    },
    {
      key: "models.temperature",
      label: "Default temperature",
      type: "number",
      file: "config.toml",
      prismTouch: "none",
      description: "Global default applied to every model unless overridden per [model.<id>]",
    },
    {
      key: "models.top_p",
      label: "Default top_p",
      type: "number",
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "models.max_completion_tokens",
      label: "Max completion tokens",
      type: "number",
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "ui.permission_mode",
      label: "Permission mode",
      type: "enum",
      enumValues: [
        "ask",
        "auto",
        "acceptEdits",
        "plan",
        "dontAsk",
        "always-approve",
        "bypassPermissions",
      ],
      file: "config.toml",
      prismTouch: "none",
      cousin: "permission-posture",
      description:
        "Product name always-approve aliases bypassPermissions; CLI --always-approve / --permission-mode",
    },
    {
      key: "ui.yolo",
      label: "Yolo (legacy always-approve)",
      type: "boolean",
      file: "config.toml",
      prismTouch: "none",
      description: "Legacy key; prefer ui.permission_mode",
    },
    {
      key: "ui.theme",
      label: "Theme",
      type: "string",
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "ui.compact_mode",
      label: "Compact mode",
      type: "boolean",
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "ui.max_thoughts_width",
      label: "Max thoughts width",
      type: "number",
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "ui.fork_secondary_model",
      label: "Fork secondary model",
      type: "string",
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "ui.screen_mode",
      label: "Default screen mode",
      type: "enum",
      enumValues: ["fullscreen", "minimal"],
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "ui.simple_mode",
      label: "Simple (readline) prompt editing",
      type: "boolean",
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "ui.vim_mode",
      label: "Vim scrollback navigation",
      type: "boolean",
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "ui.default_selected_permission",
      label: "Default selected permission row",
      type: "enum",
      enumValues: [
        "always_allow_all_sessions",
        "allow_command_always",
        "allow_once",
        "reject",
      ],
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "ui.remember_tool_approvals",
      label: "Remember tool approvals",
      type: "boolean",
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "ui.show_thinking_blocks",
      label: "Show thinking blocks",
      type: "boolean",
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "cli.auto_update",
      label: "Auto update",
      type: "boolean",
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "cli.installer",
      label: "Installer channel",
      type: "string",
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "features.telemetry",
      label: "Telemetry",
      type: "boolean",
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "features.feedback",
      label: "Feedback",
      type: "boolean",
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "features.lsp_tools",
      label: "LSP tools",
      type: "boolean",
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "features.codebase_indexing",
      label: "Codebase indexing",
      type: "boolean",
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "session.auto_compact_threshold_percent",
      label: "Auto-compact threshold %",
      type: "number",
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "session.load_envrc",
      label: "Load .envrc",
      type: "boolean",
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "tools.respect_gitignore",
      label: "Respect gitignore in tools",
      type: "boolean",
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "permission.allow",
      label: "Permission allow list",
      type: "array",
      file: "config.toml",
      prismTouch: "none",
      description: "Also mergeable from project .grok/config.toml; deny > ask > allow",
    },
    {
      key: "permission.deny",
      label: "Permission deny list",
      type: "array",
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "permission.ask",
      label: "Permission ask list",
      type: "array",
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "permission.rules",
      label: "Permission structured rules",
      type: "array",
      file: "config.toml",
      prismTouch: "none",
      description: "Object form: { action, tool, pattern }",
    },
    {
      key: "mcp_servers",
      label: "MCP servers map",
      type: "object",
      file: "config.toml",
      prismTouch: "none",
      description:
        "Project .grok/config.toml may also define mcp_servers (project wins by name)",
    },
    {
      key: "plugins.paths",
      label: "Extra plugin paths",
      type: "array",
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "plugins.disabled",
      label: "Disabled plugins",
      type: "array",
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "skills.paths",
      label: "Extra skill paths",
      type: "array",
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "skills.disabled",
      label: "Disabled skills",
      type: "array",
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "marketplace.official_marketplace_auto_installed",
      label: "Official marketplace auto-install",
      type: "boolean",
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "marketplace.sources",
      label: "Marketplace sources",
      type: "array",
      file: "config.toml",
      prismTouch: "none",
      description: "[[marketplace.sources]] entries with name + git|path",
    },
    {
      key: "compat.cursor",
      label: "Cursor harness compatibility",
      type: "object",
      file: "config.toml",
      prismTouch: "none",
      description: "Cells: skills/rules/agents/mcps/hooks/sessions (default true)",
    },
    {
      key: "compat.claude",
      label: "Claude harness compatibility",
      type: "object",
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "memory.enabled",
      label: "Memory enabled",
      type: "boolean",
      file: "config.toml",
      prismTouch: "none",
      description:
        "Experimental; default false. Priority: --no-memory > --experimental-memory > GROK_MEMORY > this key.",
    },
    {
      key: "memory.session.save_on_end",
      label: "Save session summary on end",
      type: "boolean",
      file: "config.toml",
      prismTouch: "none",
      description: "Default true. Writes a metadata summary to ~/.grok/memory/ (not .grok/).",
    },
    {
      key: "memory.watcher.enabled",
      label: "Memory file watcher",
      type: "boolean",
      file: "config.toml",
      prismTouch: "none",
      description: "Default true. Reindex ~/.grok/memory/ after external edits.",
    },
    {
      key: "memory.initial_injection.enabled",
      label: "First-turn memory injection",
      type: "boolean",
      file: "config.toml",
      prismTouch: "none",
      description: "Default true. Search+inject relevant memory on the first turn.",
    },
    {
      key: "memory.dream.enabled",
      label: "Auto dream consolidation",
      type: "boolean",
      file: "config.toml",
      prismTouch: "none",
      description: "Default true. Also /dream. Requires memory.enabled.",
    },
    {
      key: "memory.dream.min_hours",
      label: "Dream min hours",
      type: "number",
      file: "config.toml",
      prismTouch: "none",
      description: "Default 4. Minimum hours between automatic consolidations.",
    },
    {
      key: "memory.dream.min_sessions",
      label: "Dream min sessions",
      type: "number",
      file: "config.toml",
      prismTouch: "none",
      description: "Default 3. Minimum sessions since the last consolidation.",
    },
    {
      key: "compaction.memory_flush.enabled",
      label: "Pre-compaction memory flush",
      type: "boolean",
      file: "config.toml",
      prismTouch: "none",
      description: "Default true. Lives under [compaction], not [memory].",
    },
    {
      key: "subagents.enabled",
      label: "Subagents enabled",
      type: "boolean",
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "workflows.enabled",
      label: "Background workflows enabled",
      type: "boolean",
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "hints.fork_worktree_mode",
      label: "Fork worktree mode",
      type: "enum",
      enumValues: ["ask", "always", "never"],
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "hints.new_session_worktree_mode",
      label: "New-session worktree mode",
      type: "enum",
      enumValues: ["ask", "always", "never"],
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "telemetry.trace_upload",
      label: "Telemetry trace upload",
      type: "boolean",
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "telemetry.otel_enabled",
      label: "External OTEL",
      type: "boolean",
      file: "config.toml",
      prismTouch: "none",
    },
  ],
  refresh: {
    lastResearched: "2026-08-13",
    procedure: [
      "Run `grok --help` and `grok --version` (note --model, --permission-mode, --always-approve, --agent, -r)",
      "Read ~/.grok/config.toml top-level tables (redact auth / api keys / mcp env)",
      "Read ~/.grok/docs/user-guide/05-configuration.md and 22-permissions-and-safety.md if present",
      "List ~/.grok/plugins/prism-generated-* for install layout",
      "Confirm AGENTS.md still uses prism:file-router marker regions",
      "Update fields[] and lastResearched",
    ],
    sources: [
      "grok --help",
      "~/.grok/config.toml",
      "~/.grok/docs/user-guide/05-configuration.md",
      "~/.grok/docs/user-guide/13-memory.md",
      "~/.grok/docs/user-guide/22-permissions-and-safety.md",
      "~/.grok/docs/user-guide/09-plugins.md",
      "src/harnesses.ts",
      "src/lowerer-capabilities.ts",
      "src/compile/lowerers/grok.ts",
      "src/workflow-grok-worker.ts",
      "src/workflow-harness-detection.ts",
    ],
  },
  notes: [
    "Prism does not patch config.toml (no whole-file or region ownership).",
    "Rules: install-phase marker regions in AGENTS.md (prismTouch=region on that file, not config keys).",
    "Compile emits plugins/prism-generated-<plugin>/ with agents/, skills/, hooks/hooks.json.",
    "Canonical tools lower to PRISM_HOME/runtime/tools (CLI invoke), not into config.toml.",
    "Project .grok/config.toml only contributes mcp_servers, plugins, and permission rules.",
    "Workflow worker pins GROK_HOME=~/.grok and disables Cursor/Claude MCP auto-import.",
    "Live version at research time: 1.0.0 (version.json).",
    "Memory files live at ~/.grok/memory/ (global MEMORY.md + <project-slug>-<hash8>/), not project .grok/. Experimental; gated by --experimental-memory / GROK_MEMORY / --no-memory.",
    "Do not scanDirs memory from a project root — inventory handles $GROK_HOME/memory separately.",
  ],
};
