import type { HarnessCatalog } from "./types.js";

/** Hermes Agent settings catalogue — researched 2026-08-11 from live config.yaml + lowerer + CLI example. */
export const hermesCatalog: HarnessCatalog = {
  harness: "hermes",
  displayName: "Hermes Agent",
  binaryNames: ["hermes", "hermes-agent"],
  binaryEnvVars: [
    "PRISM_WORKFLOW_HERMES_BIN",
    "HERMES_HOME",
    "HERMES_ACCEPT_HOOKS",
  ],
  globalRoot: "~/.hermes/",
  projectRoot: null,
  settingsFiles: [
    {
      path: "config.yaml",
      format: "yaml",
      primary: true,
      note: "Primary settings; Prism marker-regions under hooks: only",
    },
    {
      path: "auth.json",
      format: "json",
      note: "provider OAuth/API credentials — secrets, never display",
    },
    {
      path: "SOUL.md",
      format: "md",
      note: "Identity/personality prose; not Prism-owned",
    },
    {
      path: ".env",
      format: "other",
      note: "optional secrets env; never display (api keys take precedence over config)",
    },
    {
      path: "shell-hooks-allowlist.json",
      format: "json",
      note: "first-use shell-hook consent cache; may be absent",
    },
  ],
  scanDirs: ["skills", "plugins", "hooks", "profiles", "sessions"],
  prismNamespaceMarkers: ["prism-generated-"],
  fields: [
    {
      key: "model.default",
      label: "Default model",
      type: "string",
      file: "config.yaml",
      prismTouch: "none",
      cousin: "modelspace",
      description: "CLI override: hermes chat --model; alias key model.model also accepted",
    },
    {
      key: "model.provider",
      label: "Inference provider",
      type: "string",
      file: "config.yaml",
      prismTouch: "none",
      cousin: "modelspace",
      description:
        "e.g. auto, openrouter, openai-codex, anthropic, custom, xai-oauth, nous, lmstudio; CLI --provider",
    },
    {
      key: "model.base_url",
      label: "Model base URL",
      type: "string",
      file: "config.yaml",
      prismTouch: "none",
      description: "OpenAI-compatible endpoint URL when provider is custom/local",
    },
    {
      key: "model.api_key",
      label: "Model API key",
      type: "secret",
      file: "config.yaml",
      prismTouch: "none",
      description: "Prefer env / auth.json; never surface value",
    },
    {
      key: "model.context_length",
      label: "Context length",
      type: "number",
      file: "config.yaml",
      prismTouch: "none",
      description: "Total window; leave unset for provider auto-detect",
    },
    {
      key: "model.max_tokens",
      label: "Max output tokens",
      type: "number",
      file: "config.yaml",
      prismTouch: "none",
    },
    {
      key: "fallback_providers",
      label: "Fallback providers",
      type: "array",
      file: "config.yaml",
      prismTouch: "none",
    },
    {
      key: "toolsets",
      label: "Default toolsets",
      type: "array",
      file: "config.yaml",
      prismTouch: "none",
      description: "Top-level toolset list (e.g. hermes-cli); see also platform_toolsets",
    },
    {
      key: "platform_toolsets",
      label: "Platform toolsets",
      type: "object",
      file: "config.yaml",
      prismTouch: "none",
      description: "Per-surface toolset presets: cli, telegram, discord, slack, …",
    },
    {
      key: "max_live_sessions",
      label: "Max live sessions",
      type: "number",
      file: "config.yaml",
      prismTouch: "none",
    },
    {
      key: "agent.max_turns",
      label: "Max turns",
      type: "number",
      file: "config.yaml",
      prismTouch: "none",
    },
    {
      key: "agent.reasoning_effort",
      label: "Reasoning effort",
      type: "enum",
      enumValues: ["none", "minimal", "low", "medium", "high", "xhigh", "max", "ultra"],
      file: "config.yaml",
      prismTouch: "none",
      cousin: "effort",
    },
    {
      key: "agent.verbose",
      label: "Agent verbose",
      type: "boolean",
      file: "config.yaml",
      prismTouch: "none",
    },
    {
      key: "agent.gateway_timeout",
      label: "Gateway timeout (s)",
      type: "number",
      file: "config.yaml",
      prismTouch: "none",
    },
    {
      key: "agent.tool_use_enforcement",
      label: "Tool-use enforcement",
      type: "string",
      file: "config.yaml",
      prismTouch: "none",
    },
    {
      key: "agent.verify_on_stop",
      label: "Verify on stop",
      type: "string",
      file: "config.yaml",
      prismTouch: "none",
      description: "auto | true | false; HERMES_VERIFY_ON_STOP overrides",
    },
    {
      key: "agent.coding_context",
      label: "Coding context",
      type: "string",
      file: "config.yaml",
      prismTouch: "none",
    },
    {
      key: "agent.personalities",
      label: "Named personalities",
      type: "object",
      file: "config.yaml",
      prismTouch: "none",
    },
    {
      key: "terminal.backend",
      label: "Terminal backend",
      type: "enum",
      enumValues: ["local", "ssh", "docker", "singularity", "modal", "daytona", "vercel"],
      file: "config.yaml",
      prismTouch: "none",
      description: "Sandbox boundary for tool shell; not a per-chat CLI flag",
    },
    {
      key: "terminal.cwd",
      label: "Terminal cwd",
      type: "string",
      file: "config.yaml",
      prismTouch: "none",
    },
    {
      key: "terminal.timeout",
      label: "Terminal timeout (s)",
      type: "number",
      file: "config.yaml",
      prismTouch: "none",
    },
    {
      key: "terminal.home_mode",
      label: "Terminal HOME mode",
      type: "enum",
      enumValues: ["auto", "real", "user", "profile"],
      file: "config.yaml",
      prismTouch: "none",
    },
    {
      key: "terminal.docker_image",
      label: "Docker image",
      type: "string",
      file: "config.yaml",
      prismTouch: "none",
    },
    {
      key: "terminal.lifetime_seconds",
      label: "Terminal lifetime (s)",
      type: "number",
      file: "config.yaml",
      prismTouch: "none",
    },
    {
      key: "web.backend",
      label: "Web backend",
      type: "string",
      file: "config.yaml",
      prismTouch: "none",
    },
    {
      key: "browser.engine",
      label: "Browser engine",
      type: "string",
      file: "config.yaml",
      prismTouch: "none",
    },
    {
      key: "browser.inactivity_timeout",
      label: "Browser inactivity timeout",
      type: "number",
      file: "config.yaml",
      prismTouch: "none",
    },
    {
      key: "checkpoints.enabled",
      label: "Checkpoints enabled",
      type: "boolean",
      file: "config.yaml",
      prismTouch: "none",
    },
    {
      key: "compression.enabled",
      label: "Context compression",
      type: "boolean",
      file: "config.yaml",
      prismTouch: "none",
    },
    {
      key: "compression.threshold",
      label: "Compression threshold",
      type: "number",
      file: "config.yaml",
      prismTouch: "none",
      description: "Fraction of context_length that triggers compression",
    },
    {
      key: "compression.target_ratio",
      label: "Compression target ratio",
      type: "number",
      file: "config.yaml",
      prismTouch: "none",
    },
    {
      key: "prompt_caching.cache_ttl",
      label: "Prompt cache TTL",
      type: "string",
      file: "config.yaml",
      prismTouch: "none",
    },
    {
      key: "openrouter.response_cache",
      label: "OpenRouter response cache",
      type: "boolean",
      file: "config.yaml",
      prismTouch: "none",
    },
    {
      key: "auxiliary",
      label: "Auxiliary task models",
      type: "object",
      file: "config.yaml",
      prismTouch: "none",
      description:
        "Per-task provider/model blocks: vision, compression, skills_hub, approval, title_generation, curator, …",
    },
    {
      key: "display.personality",
      label: "Display personality",
      type: "string",
      file: "config.yaml",
      prismTouch: "none",
      description: "Selects agent.personalities.* key or built-in name",
    },
    {
      key: "display.interface",
      label: "Interface mode",
      type: "string",
      file: "config.yaml",
      prismTouch: "none",
      description: "e.g. cli, tui",
    },
    {
      key: "display.streaming",
      label: "Streaming",
      type: "boolean",
      file: "config.yaml",
      prismTouch: "none",
    },
    {
      key: "display.show_reasoning",
      label: "Show reasoning",
      type: "boolean",
      file: "config.yaml",
      prismTouch: "none",
    },
    {
      key: "display.compact",
      label: "Compact display",
      type: "boolean",
      file: "config.yaml",
      prismTouch: "none",
    },
    {
      key: "display.skin",
      label: "Skin",
      type: "string",
      file: "config.yaml",
      prismTouch: "none",
    },
    {
      key: "display.tool_progress",
      label: "Tool progress mode",
      type: "string",
      file: "config.yaml",
      prismTouch: "none",
    },
    {
      key: "privacy.redact_pii",
      label: "Redact PII",
      type: "boolean",
      file: "config.yaml",
      prismTouch: "none",
    },
    {
      key: "memory.memory_enabled",
      label: "Memory enabled",
      type: "boolean",
      file: "config.yaml",
      prismTouch: "none",
    },
    {
      key: "memory.write_approval",
      label: "Memory write approval",
      type: "boolean",
      file: "config.yaml",
      prismTouch: "none",
    },
    {
      key: "delegation.max_iterations",
      label: "Delegation max iterations",
      type: "number",
      file: "config.yaml",
      prismTouch: "none",
    },
    {
      key: "delegation.max_concurrent_children",
      label: "Max concurrent subagents",
      type: "number",
      file: "config.yaml",
      prismTouch: "none",
    },
    {
      key: "skills.external_dirs",
      label: "External skill dirs",
      type: "array",
      file: "config.yaml",
      prismTouch: "none",
    },
    {
      key: "skills.write_approval",
      label: "Skill write approval",
      type: "boolean",
      file: "config.yaml",
      prismTouch: "none",
    },
    {
      key: "approvals.mode",
      label: "Approvals mode",
      type: "string",
      file: "config.yaml",
      prismTouch: "none",
      cousin: "permission-posture",
      description:
        "Config-scoped approval gate; CLI --yolo bypasses for a session. No per-task restricted flag.",
    },
    {
      key: "approvals.timeout",
      label: "Approvals timeout (s)",
      type: "number",
      file: "config.yaml",
      prismTouch: "none",
    },
    {
      key: "approvals.cron_mode",
      label: "Cron approvals mode",
      type: "string",
      file: "config.yaml",
      prismTouch: "none",
    },
    {
      key: "command_allowlist",
      label: "Command allowlist",
      type: "array",
      file: "config.yaml",
      prismTouch: "none",
      cousin: "permission-posture",
    },
    {
      key: "hooks_auto_accept",
      label: "Hooks auto-accept",
      type: "boolean",
      file: "config.yaml",
      prismTouch: "none",
      description: "Non-interactive consent for shell hooks; also HERMES_ACCEPT_HOOKS / --accept-hooks",
    },
    {
      key: "hooks",
      label: "Shell hooks map",
      type: "object",
      file: "config.yaml",
      prismTouch: "region",
      description:
        "Native events: pre_tool_call, post_tool_call, pre_llm_call, on_session_start, on_session_end, subagent_stop, …. Prism patches marker regions hermes.hooks.<event> under hooks: and writes wrappers to plugins/prism-generated-<plugin>/hooks/*.mjs",
    },
    {
      key: "security.tirith_enabled",
      label: "Tirith security scan",
      type: "boolean",
      file: "config.yaml",
      prismTouch: "none",
    },
    {
      key: "security.redact_secrets",
      label: "Redact secrets",
      type: "boolean",
      file: "config.yaml",
      prismTouch: "none",
    },
    {
      key: "security.allow_private_urls",
      label: "Allow private URLs",
      type: "boolean",
      file: "config.yaml",
      prismTouch: "none",
    },
    {
      key: "mcp_servers",
      label: "MCP servers",
      type: "object",
      file: "config.yaml",
      prismTouch: "none",
      description:
        "Optional YAML map of MCP servers (command/url). Sync engine can marker-region under mcp_servers:; Hermes lowerer does not currently emit Prism MCP entries (tools use CLI runtime under PRISM_HOME)",
    },
    {
      key: "mcp_discovery_timeout",
      label: "MCP discovery timeout",
      type: "number",
      file: "config.yaml",
      prismTouch: "none",
    },
    {
      key: "plugins.enabled",
      label: "Enabled plugins",
      type: "array",
      file: "config.yaml",
      prismTouch: "none",
      description: "Native Hermes Python plugins under plugins/; not Prism-generated bundles",
    },
    {
      key: "custom_providers",
      label: "Custom providers",
      type: "array",
      file: "config.yaml",
      prismTouch: "none",
      description: "Named OpenAI-compatible providers; entries may hold api_key secrets — redact",
    },
    {
      key: "gateway.strict",
      label: "Gateway strict mode",
      type: "boolean",
      file: "config.yaml",
      prismTouch: "none",
    },
    {
      key: "gateway.scale_to_zero.idle_timeout_minutes",
      label: "Gateway idle timeout (min)",
      type: "number",
      file: "config.yaml",
      prismTouch: "none",
    },
    {
      key: "logging.level",
      label: "Log level",
      type: "string",
      file: "config.yaml",
      prismTouch: "none",
    },
    {
      key: "sessions.auto_prune",
      label: "Session auto-prune",
      type: "boolean",
      file: "config.yaml",
      prismTouch: "none",
    },
    {
      key: "sessions.retention_days",
      label: "Session retention days",
      type: "number",
      file: "config.yaml",
      prismTouch: "none",
    },
    {
      key: "cron.output_retention",
      label: "Cron output retention",
      type: "number",
      file: "config.yaml",
      prismTouch: "none",
    },
    {
      key: "kanban.dispatch_in_gateway",
      label: "Kanban dispatch in gateway",
      type: "boolean",
      file: "config.yaml",
      prismTouch: "none",
    },
    {
      key: "code_execution.mode",
      label: "Code execution mode",
      type: "string",
      file: "config.yaml",
      prismTouch: "none",
    },
    {
      key: "tool_loop_guardrails.warnings_enabled",
      label: "Tool-loop warnings",
      type: "boolean",
      file: "config.yaml",
      prismTouch: "none",
    },
    {
      key: "tool_loop_guardrails.hard_stop_enabled",
      label: "Tool-loop hard stop",
      type: "boolean",
      file: "config.yaml",
      prismTouch: "none",
    },
    {
      key: "file_read_max_chars",
      label: "File read max chars",
      type: "number",
      file: "config.yaml",
      prismTouch: "none",
    },
    {
      key: "worktree",
      label: "Always use git worktree",
      type: "boolean",
      file: "config.yaml",
      prismTouch: "none",
      description: "Documented in cli-config.yaml.example; may be absent until set",
    },
    {
      key: "dashboard.oauth",
      label: "Dashboard OAuth",
      type: "object",
      file: "config.yaml",
      prismTouch: "none",
      description: "client_id/portal_url — treat as sensitive",
    },
    {
      key: "dashboard.basic_auth",
      label: "Dashboard basic auth",
      type: "object",
      file: "config.yaml",
      prismTouch: "none",
      description: "password/password_hash/secret — secrets, never display",
    },
    {
      key: "secrets",
      label: "Secrets backends",
      type: "object",
      file: "config.yaml",
      prismTouch: "none",
      description: "e.g. bitwarden integration; never display tokens",
    },
    {
      key: "_config_version",
      label: "Config schema version",
      type: "number",
      file: "config.yaml",
      prismTouch: "none",
      description: "Hermes-managed migration marker",
    },
  ],
  refresh: {
    lastResearched: "2026-08-11",
    procedure: [
      "Run `hermes --help` and `hermes chat --help`; note --model/--provider/--profile/--yolo/-Q/--accept-hooks",
      "Read ~/.hermes/config.yaml top-level + nested keys (redact api_key, auth.json, custom_providers[].api_key, dashboard.basic_auth)",
      "Diff against hermes-agent/cli-config.yaml.example for newly documented keys",
      "Confirm Prism hooks surface: src/compile/lowerers/hermes.ts regions under hooks: + plugins/prism-generated-*/hooks/",
      "Confirm skills install path: <hermes-root>/skills/ and profile roots ~/.hermes/profiles/<name>/",
      "Check lowerer-capabilities.ts hermes entry for surface changes",
      "Update fields[] and lastResearched",
    ],
    sources: [
      "hermes --help / hermes chat --help",
      "~/.hermes/config.yaml",
      "~/.hermes/hermes-agent/cli-config.yaml.example",
      "~/.hermes/hermes-agent/hermes_cli/_parser.py",
      "src/harnesses.ts",
      "src/lowerer-capabilities.ts",
      "src/compile/lowerers/hermes.ts",
      "src/compile/hook-capabilities.ts",
      "src/workflow-hermes-worker.ts",
      "src/workflow-harness-detection.ts",
    ],
  },
  notes: [
    "Skills-only + hooks + CLI tools: no rules, commands, or compiled agents (agents fail-closed).",
    "Canonical tools lower to <PRISM_HOME>/runtime/tools/<plugin>/; invoke via `prism tools invoke` (not native Hermes Python plugins).",
    "Prism patches config.yaml only for hooks: marker regions (hermes.hooks.<nativeEvent>); does not whole-file own config.yaml.",
    "Hook wrappers live under plugins/prism-generated-<plugin>/hooks/*.mjs; native Python plugins/ is a separate Hermes surface.",
    "Profiles are alternate HERMES_HOME roots: ~/.hermes/profiles/<name>/ (own config.yaml + skills/). Use --profile or --compile-root for profile installs.",
    "projectRoot is null — Hermes is user/profile-scoped, not project-.hermes/.",
    "Workflow worker: hermes chat --query … -Q [--model] [--provider] [--yolo]; permission modes restricted/sandbox/interactive unsupported.",
    "custom_providers and model.api_key may hold plaintext secrets in live YAML — always redact in inventory previews.",
  ],
};
