import type { HarnessCatalog } from "./types.js";

/** Kimi Code settings catalogue — researched 2026-08-11 from live ~/.kimi-code + lowerer. */
export const kimiCodeCatalog: HarnessCatalog = {
  harness: "kimi-code",
  displayName: "Kimi Code",
  binaryNames: ["kimi"],
  binaryEnvVars: ["PRISM_WORKFLOW_KIMI_BIN", "KIMI_CODE_HOME"],
  globalRoot: "~/.kimi-code/",
  projectRoot: null,
  settingsFiles: [
    {
      path: "config.toml",
      format: "toml",
      primary: true,
      note: "Agent/runtime settings; Prism marker-patches [[hooks]] only",
    },
    {
      path: "tui.toml",
      format: "toml",
      note: "Client/TUI prefs; Prism does not touch",
    },
    {
      path: "plugins/installed.json",
      format: "json",
      note: "Plugin registry; Prism owns prism-generated-* array members + version key",
    },
    {
      path: "credentials/kimi-code.json",
      format: "json",
      note: "secrets — never display",
    },
    {
      path: "oauth/kimi-code",
      format: "other",
      note: "OAuth token store (file path referenced by config.toml oauth.key)",
    },
  ],
  scanDirs: ["plugins", "skills", "hooks"],
  prismNamespaceMarkers: ["prism-generated-"],
  fields: [
    {
      key: "default_model",
      label: "Default model",
      type: "string",
      file: "config.toml",
      prismTouch: "none",
      cousin: "modelspace",
      description: "Live default e.g. kimi-code/kimi-for-coding",
    },
    {
      key: "thinking.enabled",
      label: "Thinking enabled",
      type: "boolean",
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "hooks",
      label: "Hooks table ([[hooks]])",
      type: "array",
      file: "config.toml",
      prismTouch: "region",
      description:
        "Array of {event, command, timeout?, matcher?}. Prism writes marker regions keyed kimi.hooks.<plugin> for compile-phase hooks; herdr and other user hooks coexist outside those regions.",
    },
    {
      key: "providers.managed:kimi-code.type",
      label: "Managed provider type",
      type: "string",
      file: "config.toml",
      prismTouch: "none",
      description: 'TOML table [providers."managed:kimi-code"]; type is typically "kimi"',
    },
    {
      key: "providers.managed:kimi-code.base_url",
      label: "Managed provider base URL",
      type: "string",
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "providers.managed:kimi-code.api_key",
      label: "Managed provider API key",
      type: "secret",
      file: "config.toml",
      prismTouch: "none",
      description: "Often empty when oauth is used",
    },
    {
      key: "providers.managed:kimi-code.oauth",
      label: "Managed provider OAuth",
      type: "object",
      file: "config.toml",
      prismTouch: "none",
      description: '{ storage: "file", key: "oauth/kimi-code" }',
    },
    {
      key: "services.moonshot_search.base_url",
      label: "Moonshot search base URL",
      type: "string",
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "services.moonshot_search.api_key",
      label: "Moonshot search API key",
      type: "secret",
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "services.moonshot_search.oauth",
      label: "Moonshot search OAuth",
      type: "object",
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "services.moonshot_fetch.base_url",
      label: "Moonshot fetch base URL",
      type: "string",
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "services.moonshot_fetch.api_key",
      label: "Moonshot fetch API key",
      type: "secret",
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "services.moonshot_fetch.oauth",
      label: "Moonshot fetch OAuth",
      type: "object",
      file: "config.toml",
      prismTouch: "none",
    },
    {
      key: "models",
      label: "Model definitions",
      type: "object",
      file: "config.toml",
      prismTouch: "none",
      cousin: "modelspace",
      description:
        "Map of model id → {provider, model, max_context_size, capabilities[], display_name}. Live: kimi-code/kimi-for-coding, kimi-code/kimi-for-coding-highspeed",
    },
    {
      key: "theme",
      label: "TUI theme",
      type: "enum",
      enumValues: ["auto", "dark", "light"],
      file: "tui.toml",
      prismTouch: "none",
      description: "Also accepts custom theme names",
    },
    {
      key: "editor.command",
      label: "External editor command",
      type: "string",
      file: "tui.toml",
      prismTouch: "none",
      description: "Empty uses $VISUAL / $EDITOR",
    },
    {
      key: "notifications.enabled",
      label: "Notifications enabled",
      type: "boolean",
      file: "tui.toml",
      prismTouch: "none",
    },
    {
      key: "notifications.notification_condition",
      label: "Notification condition",
      type: "enum",
      enumValues: ["unfocused", "always"],
      file: "tui.toml",
      prismTouch: "none",
    },
    {
      key: "upgrade.auto_install",
      label: "Auto-install upgrades",
      type: "boolean",
      file: "tui.toml",
      prismTouch: "none",
    },
    {
      key: "version",
      label: "Installed plugins schema version",
      type: "number",
      file: "plugins/installed.json",
      prismTouch: "region",
      description: "Prism sets version: 1 via json-key region installed.version",
    },
    {
      key: "plugins",
      label: "Installed plugins list",
      type: "array",
      file: "plugins/installed.json",
      prismTouch: "region",
      description:
        "Each member {id, root, source, enabled, installedAt, originalSource?}. Prism owns prism-generated-* members by id; user enable/disable of those members is preserved on re-register",
    },
  ],
  refresh: {
    lastResearched: "2026-08-11",
    procedure: [
      "Run `kimi --help` and `kimi --version` (bin via PATH or PRISM_WORKFLOW_KIMI_BIN)",
      "Read ~/.kimi-code/config.toml top-level + [thinking]/[providers.*]/[models.*]/[services.*] and [[hooks]] (redact api_key)",
      "Read ~/.kimi-code/tui.toml client prefs",
      "Read ~/.kimi-code/plugins/installed.json version + plugins[] shape",
      "Inspect plugins/managed/prism-generated-*/kimi.plugin.json + skills/hooks layout",
      "Diff against src/compile/lowerers/kimi-code.ts marker/json regions",
      "Update fields[] and lastResearched",
    ],
    sources: [
      "kimi --help",
      "~/.kimi-code/config.toml",
      "~/.kimi-code/tui.toml",
      "~/.kimi-code/plugins/installed.json",
      "~/.kimi-code/plugins/managed/prism-generated-*/kimi.plugin.json",
      "src/harnesses.ts",
      "src/lowerer-capabilities.ts",
      "src/compile/lowerers/kimi-code.ts",
      "src/workflow-kimi-worker.ts",
      "src/workflow-harness-detection.ts",
    ],
  },
  notes: [
    "Global root is ~/.kimi-code only (override with KIMI_CODE_HOME). Prism project scope is unsupported for this lowerer.",
    "Moonshot docs also mention project-local .kimi-code/skills and .kimi-code/mcp.json; Prism does not mix those with generated user-scoped plugin bundles.",
    "Prism does not whole-file own config.toml or tui.toml. Hooks: marker regions (commentPrefix #, regionKey kimi.hooks.<plugin>). installed.json: json-key version + json-array-member by plugins[].id.",
    "Generated layout: plugins/managed/prism-generated-<plugin>/{kimi.plugin.json,skills/,hooks/}. Rules → skills/prism-context (sessionStart.skill); agents → skills/prism-agent-*; commands → skills/prism-command-* (type flow).",
    "Kimi's own manager may add plugin.json (symlink) and prism.lock inside generated plugins — doctor allows those as harness manager artifacts.",
    "Canonical tools lower to PRISM_HOME/runtime/tools (CLI invoke), not MCP config. Workflow worker: kimi --prompt --output-format stream-json --skills-dir … (no --yolo with --prompt).",
    "Native hook events observed: SessionStart, SessionEnd, UserPromptSubmit, PreToolUse, PostToolUse (Prism maps tool.before/after), SubagentStart, PreCompact, PermissionRequest, PermissionResult, Stop, Interrupt.",
    "Auth: OAuth via kimi login / credentials + oauth/kimi-code file store; empty api_key fields are normal when oauth is active.",
  ],
};
