import type { HarnessCatalog } from "./types.js";

/**
 * Oh My Pi (omp) settings catalogue.
 * Researched 2026-08-13 from live ~/.omp/agent/config.yml, oh-my-pi SETTINGS_SCHEMA,
 * harness registry, lowerer capabilities, and workflow worker flags.
 */
export const ompCatalog: HarnessCatalog = {
  harness: "omp",
  displayName: "Oh My Pi",
  binaryNames: ["omp"],
  binaryEnvVars: ["PRISM_WORKFLOW_OMP_BIN"],
  globalRoot: "~/.omp/agent/",
  projectRoot: ".omp/",
  settingsFiles: [
    {
      path: "config.yml",
      format: "yaml",
      primary: true,
      note: "User settings; Prism never patches this file",
    },
    {
      path: "mcp.json",
      format: "json",
      note: "Optional MCP server map (also .mcp.json / project .omp/mcp.json)",
    },
    {
      path: "agents/*.md",
      format: "md",
      note: "Compiled agents with YAML frontmatter (model, thinkingLevel, tools, …)",
    },
  ],
  scanDirs: [
    "agents",
    "skills",
    "commands",
    "rules",
    "extensions",
    "sessions",
    "terminal-sessions",
  ],
  prismNamespaceMarkers: ["prism-generated-"],
  fields: [
    // ── Present on live config.yml ─────────────────────────────────────────
    {
      key: "modelRoles",
      label: "Model roles",
      type: "object",
      file: "config.yml",
      prismTouch: "none",
      cousin: "modelspace",
      description:
        "Record of logical role → provider/model id (e.g. default, smol, advisor). Live: modelRoles.default",
    },
    {
      key: "modelRoles.default",
      label: "Default model role",
      type: "string",
      file: "config.yml",
      prismTouch: "none",
      cousin: "model",
      description: "Primary model binding used when no --model flag is set",
    },
    {
      key: "defaultThinkingLevel",
      label: "Default thinking level",
      type: "enum",
      enumValues: ["off", "minimal", "low", "medium", "high", "xhigh", "max", "auto"],
      file: "config.yml",
      prismTouch: "none",
      cousin: "effort",
    },
    {
      key: "symbolPreset",
      label: "Symbol preset",
      type: "enum",
      enumValues: ["unicode", "nerd", "ascii"],
      file: "config.yml",
      prismTouch: "none",
    },
    {
      key: "theme.dark",
      label: "Dark theme",
      type: "string",
      file: "config.yml",
      prismTouch: "none",
    },
    {
      key: "theme.light",
      label: "Light theme",
      type: "string",
      file: "config.yml",
      prismTouch: "none",
    },
    {
      key: "setupVersion",
      label: "Setup version",
      type: "number",
      file: "config.yml",
      prismTouch: "none",
      description: "Onboarding / setup-wizard completion marker",
    },
    {
      key: "dev.autoqa.consent",
      label: "Auto QA consent",
      type: "string",
      file: "config.yml",
      prismTouch: "none",
      description: "Live key under dev.autoqa; Auto QA telemetry consent",
    },

    // ── High-value schema keys (SETTINGS_SCHEMA) ───────────────────────────
    {
      key: "tools.approvalMode",
      label: "Tool approval mode",
      type: "enum",
      enumValues: ["always-ask", "write", "yolo"],
      file: "config.yml",
      prismTouch: "none",
      cousin: "permission-posture",
      description:
        "Default approval tier. Workflow worker maps permissive/full-access → --approval-mode yolo",
    },
    {
      key: "tools.approval",
      label: "Per-tool approval policies",
      type: "object",
      file: "config.yml",
      prismTouch: "none",
      description: "Record of tool name → allow | prompt | deny",
    },
    {
      key: "autoResume",
      label: "Auto resume last session",
      type: "boolean",
      file: "config.yml",
      prismTouch: "none",
    },
    {
      key: "extensions",
      label: "Extension paths",
      type: "array",
      file: "config.yml",
      prismTouch: "none",
      description:
        "Extra extension path list in config; Prism installs under extensions/prism-generated-<plugin>/ via native discovery, not this array",
    },
    {
      key: "disabledExtensions",
      label: "Disabled extensions",
      type: "array",
      file: "config.yml",
      prismTouch: "none",
    },
    {
      key: "enabledModels",
      label: "Enabled model patterns",
      type: "array",
      file: "config.yml",
      prismTouch: "none",
      cousin: "modelspace",
    },
    {
      key: "disabledProviders",
      label: "Disabled providers",
      type: "array",
      file: "config.yml",
      prismTouch: "none",
    },
    {
      key: "modelTags",
      label: "Model tags",
      type: "object",
      file: "config.yml",
      prismTouch: "none",
    },
    {
      key: "modelProviderOrder",
      label: "Model provider order",
      type: "array",
      file: "config.yml",
      prismTouch: "none",
    },
    {
      key: "personality",
      label: "Personality",
      type: "enum",
      enumValues: ["default", "friendly", "pragmatic", "none"],
      file: "config.yml",
      prismTouch: "none",
    },
    {
      key: "advisor.enabled",
      label: "Advisor enabled",
      type: "boolean",
      file: "config.yml",
      prismTouch: "none",
    },
    {
      key: "power.sleepPrevention",
      label: "macOS sleep prevention",
      type: "enum",
      enumValues: ["off", "idle", "display", "system"],
      file: "config.yml",
      prismTouch: "none",
    },
    {
      key: "memory.backend",
      label: "Memory backend",
      type: "enum",
      enumValues: ["off", "local", "hindsight", "mnemopi"],
      file: "config.yml",
      prismTouch: "none",
      description:
        "Default off. local writes ~/.omp/agent/memories/<encoded-cwd>/ — project .omp/ is config, not the store. Legacy memories.enabled migrates to local|off.",
    },
    {
      key: "autolearn.enabled",
      label: "Autolearn (learn tool)",
      type: "boolean",
      file: "config.yml",
      prismTouch: "none",
      description: "When true, exposes the learn tool (local backend writes learned.md).",
    },
    {
      key: "skills.enabled",
      label: "Skills enabled",
      type: "boolean",
      file: "config.yml",
      prismTouch: "none",
    },
    {
      key: "skills.enableSkillCommands",
      label: "Skill slash commands",
      type: "boolean",
      file: "config.yml",
      prismTouch: "none",
      description: "Register skills as /skill:name commands",
    },
    {
      key: "statusLine.preset",
      label: "Status line preset",
      type: "enum",
      enumValues: ["default", "minimal", "compact", "full", "nerd", "ascii", "custom"],
      file: "config.yml",
      prismTouch: "none",
    },
    {
      key: "hideThinkingBlock",
      label: "Hide thinking blocks",
      type: "boolean",
      file: "config.yml",
      prismTouch: "none",
    },
    {
      key: "auth.broker.url",
      label: "Auth broker URL",
      type: "string",
      file: "config.yml",
      prismTouch: "none",
      description: "Optional; env OMP_AUTH_BROKER_URL overrides",
    },
    {
      key: "auth.broker.token",
      label: "Auth broker token",
      type: "secret",
      file: "config.yml",
      prismTouch: "none",
      description: "Secret — never display; env OMP_AUTH_BROKER_TOKEN overrides",
    },
    {
      key: "shellPath",
      label: "Shell path",
      type: "string",
      file: "config.yml",
      prismTouch: "none",
    },
    {
      key: "git.enabled",
      label: "Git integration",
      type: "boolean",
      file: "config.yml",
      prismTouch: "none",
    },
    {
      key: "providers.maxInFlightRequests",
      label: "Max in-flight requests per provider",
      type: "object",
      file: "config.yml",
      prismTouch: "none",
    },

    // ── MCP (separate file) ────────────────────────────────────────────────
    {
      key: "mcpServers",
      label: "MCP servers",
      type: "object",
      file: "mcp.json",
      prismTouch: "none",
      description: "Map of server name → http|stdio config; secrets may appear in env/headers",
    },
    {
      key: "disabledServers",
      label: "Disabled MCP servers",
      type: "array",
      file: "mcp.json",
      prismTouch: "none",
    },

    // ── Compiled agent frontmatter (Prism-owned whole files) ───────────────
    {
      key: "model",
      label: "Agent model",
      type: "string",
      file: "agents/*.md",
      prismTouch: "owned",
      cousin: "modelspace",
      description:
        "YAML frontmatter on compiled agents; string or string[] from modelspace / targets.omp",
    },
    {
      key: "thinkingLevel",
      label: "Agent thinking level",
      type: "enum",
      enumValues: ["off", "minimal", "low", "medium", "high", "xhigh", "max", "auto"],
      file: "agents/*.md",
      prismTouch: "owned",
      cousin: "effort",
    },
    {
      key: "tools",
      label: "Agent tools allowlist",
      type: "array",
      file: "agents/*.md",
      prismTouch: "owned",
      description: "Includes harness tools plus Prism CLI tool names (plugin_tool)",
    },
    {
      key: "autoloadSkills",
      label: "Agent autoload skills",
      type: "array",
      file: "agents/*.md",
      prismTouch: "owned",
    },
    {
      key: "spawns",
      label: "Agent spawn allowlist",
      type: "array",
      file: "agents/*.md",
      prismTouch: "owned",
      description: "Other agent names this agent may spawn, or *",
    },
    {
      key: "readSummarize",
      label: "Agent read-summarize",
      type: "boolean",
      file: "agents/*.md",
      prismTouch: "owned",
    },
  ],
  refresh: {
    lastResearched: "2026-08-13",
    procedure: [
      "Run `omp --help` (and scripting flags: --mode json, --approval-mode, --model, --thinking, --profile, --resume)",
      "Read ~/.omp/agent/config.yml top-level keys (redact auth.broker.token and any secrets)",
      "Diff against oh-my-pi packages/coding-agent/src/config/settings-schema.ts SETTINGS_SCHEMA",
      "List ~/.omp/agent/extensions/prism-generated-* and agents/, skills/ for install layout",
      "Confirm src/compile/lowerers/omp.ts still emits agents + skills + extensions only (no config.yml regions)",
      "Update fields[] and lastResearched",
    ],
    sources: [
      "omp --help",
      "~/.omp/agent/config.yml",
      "~/.omp/agent/mcp.json",
      "oh-my-pi packages/coding-agent/src/config/settings-schema.ts",
      "https://github.com/can1357/oh-my-pi/blob/main/docs/memory.md",
      "src/harnesses.ts (omp entry)",
      "src/lowerer-capabilities.ts (omp)",
      "src/compile/lowerers/omp.ts",
      "src/workflow-omp-worker.ts",
      "src/refresh.ts (COMPILE_MANAGED_RULE_HARNESSES / COMMANDS includes omp)",
    ],
  },
  notes: [
    "Distinct from Pi: global root is ~/.omp/agent/ (not ~/.pi); project root is .omp/.",
    "Parent ~/.omp/ holds logs/, profiles/, cache, install-id — not the harness agent root.",
    "Prism does not whole-file own or region-patch config.yml; lowerer returns regions: [].",
    "Install layout: agents/<name>.md, skills/<name>/, extensions/prism-generated-<plugin>/index.ts (+ hooks/).",
    "Rules/commands are declared compile-managed in refresh.ts and lowerer-capabilities, but omp.ts currently does not plan rules/ or commands/ writes — treat as capability claim until lowerer gains them.",
    "Workflow worker: PRISM_WORKFLOW_OMP_BIN || omp; --mode json --append-system-prompt <agent.md> --approval-mode yolo (permissive/full-access).",
    "Profiles live under ~/.omp/profiles/<name>/agent/ and are selected via --profile.",
    "Agent skill permission surface is unsupported; permission-only skill access fails closed at compile.",
    "memory.backend default off. local backend writes ~/.omp/agent/memories/<encoded-cwd>/; project .omp/ is config, not the memory store.",
  ],
};
