import type { HarnessCatalog } from "./types.js";

/**
 * OpenCode settings catalogue — researched 2026-08-11 from live
 * ~/.config/opencode/opencode.json + tui.json, official config schema
 * (https://opencode.ai/config.json), harness registry, and compile lowerer.
 */
export const opencodeCatalog: HarnessCatalog = {
  harness: "opencode",
  displayName: "OpenCode",
  binaryNames: ["opencode"],
  binaryEnvVars: ["PRISM_WORKFLOW_OPENCODE_BIN"],
  globalRoot: "~/.config/opencode/",
  projectRoot: ".opencode/",
  settingsFiles: [
    {
      path: "opencode.json",
      format: "json",
      primary: true,
      note: "Shared user config; Prism patches agent.<name> keys, plugin array members, and permission.<ns>_* only",
    },
    {
      path: "AGENTS.md",
      format: "md",
      note: "Rules; Prism marker regions (prism:file-router...)",
    },
    {
      path: "tui.json",
      format: "json",
      note: "TUI-only settings (theme, keybinds, scroll); Prism does not patch",
    },
    {
      path: "package.json",
      format: "json",
      note: "Local @opencode-ai/plugin dep for generated plugins; not a settings surface",
    },
  ],
  scanDirs: ["agents", "commands", "skills", "plugins", "plugin"],
  prismNamespaceMarkers: ["prism-generated-"],
  fields: [
    // --- Present on live disk (2026-08-11) ---
    {
      key: "$schema",
      label: "JSON Schema",
      type: "string",
      file: "opencode.json",
      prismTouch: "none",
      description: "Typically https://opencode.ai/config.json",
    },
    {
      key: "model",
      label: "Default model",
      type: "string",
      file: "opencode.json",
      prismTouch: "none",
      cousin: "modelspace",
      description: "provider/model (e.g. anthropic/claude-sonnet-4); absent on this machine — agents carry their own models",
    },
    {
      key: "small_model",
      label: "Small model",
      type: "string",
      file: "opencode.json",
      prismTouch: "none",
      cousin: "modelspace",
      description: "Titles and light tasks; live: firepass/…/kimi-k2p6-turbo",
    },
    {
      key: "default_agent",
      label: "Default agent",
      type: "string",
      file: "opencode.json",
      prismTouch: "none",
      description: "Primary agent when none specified; falls back to build",
    },
    {
      key: "agent",
      label: "Agent map",
      type: "object",
      file: "opencode.json",
      prismTouch: "region",
      cousin: "modelspace",
      description:
        "Per-agent blocks. Prism owns only compiler keys under agent.<name> (model, variant, mode, color, permission, temperature, top_p, maxSteps, disable) as json-key regions; hand-authored sibling keys preserved",
    },
    {
      key: "agent.<name>.model",
      label: "Agent model",
      type: "string",
      file: "opencode.json",
      prismTouch: "region",
      cousin: "modelspace",
    },
    {
      key: "agent.<name>.variant",
      label: "Agent model variant",
      type: "string",
      file: "opencode.json",
      prismTouch: "region",
    },
    {
      key: "agent.<name>.mode",
      label: "Agent mode",
      type: "enum",
      enumValues: ["subagent", "primary", "all"],
      file: "opencode.json",
      prismTouch: "region",
    },
    {
      key: "agent.<name>.color",
      label: "Agent color",
      type: "string",
      file: "opencode.json",
      prismTouch: "region",
    },
    {
      key: "agent.<name>.temperature",
      label: "Agent temperature",
      type: "number",
      file: "opencode.json",
      prismTouch: "region",
    },
    {
      key: "agent.<name>.top_p",
      label: "Agent top_p",
      type: "number",
      file: "opencode.json",
      prismTouch: "region",
    },
    {
      key: "agent.<name>.maxSteps",
      label: "Agent max steps",
      type: "number",
      file: "opencode.json",
      prismTouch: "region",
      description: "Deprecated upstream in favor of steps; still compiler-owned",
    },
    {
      key: "agent.<name>.disable",
      label: "Agent disabled",
      type: "boolean",
      file: "opencode.json",
      prismTouch: "region",
    },
    {
      key: "agent.<name>.permission",
      label: "Agent permission overrides",
      type: "object",
      file: "opencode.json",
      prismTouch: "region",
      cousin: "permission-posture",
    },
    {
      key: "permission",
      label: "Global permission map",
      type: "object",
      file: "opencode.json",
      prismTouch: "region",
      cousin: "permission-posture",
      description:
        "ask|allow|deny rules for tools. Prism only patches permission.<plugin_ns>_* = deny for generated tool namespaces; user bash/edit/etc. rules are hand-owned",
    },
    {
      key: "permission.bash",
      label: "Bash permission rules",
      type: "object",
      file: "opencode.json",
      prismTouch: "none",
    },
    {
      key: "permission.edit",
      label: "Edit permission",
      type: "enum",
      enumValues: ["ask", "allow", "deny"],
      file: "opencode.json",
      prismTouch: "none",
    },
    {
      key: "permission.read",
      label: "Read permission",
      type: "enum",
      enumValues: ["ask", "allow", "deny"],
      file: "opencode.json",
      prismTouch: "none",
    },
    {
      key: "permission.write",
      label: "Write permission",
      type: "enum",
      enumValues: ["ask", "allow", "deny"],
      file: "opencode.json",
      prismTouch: "none",
    },
    {
      key: "permission.external_directory",
      label: "External directory permission",
      type: "enum",
      enumValues: ["ask", "allow", "deny"],
      file: "opencode.json",
      prismTouch: "none",
    },
    {
      key: "permission.doom_loop",
      label: "Doom-loop permission",
      type: "enum",
      enumValues: ["ask", "allow", "deny"],
      file: "opencode.json",
      prismTouch: "none",
    },
    {
      key: "permission.<ns>_*",
      label: "Generated tool namespace deny",
      type: "enum",
      enumValues: ["ask", "allow", "deny"],
      file: "opencode.json",
      prismTouch: "region",
      description:
        "Deny-by-default for Prism-generated tool namespaces (e.g. tower_*, quasar_*); json-key region per plugin",
    },
    {
      key: "plugin",
      label: "Plugin array",
      type: "array",
      file: "opencode.json",
      prismTouch: "region",
      description:
        "String or [path, options] entries. Prism owns json-array-member regions for file://…/plugins/prism-generated-<plugin>/dist/server.mjs only",
    },
    {
      key: "mcp",
      label: "MCP servers",
      type: "object",
      file: "opencode.json",
      prismTouch: "none",
      description: "Local/remote MCP configs; may embed env secrets — redact",
    },
    {
      key: "provider",
      label: "Provider overrides",
      type: "object",
      file: "opencode.json",
      prismTouch: "none",
      description: "Custom provider/model config; apiKey is secret",
    },
    {
      key: "disabled_providers",
      label: "Disabled providers",
      type: "array",
      file: "opencode.json",
      prismTouch: "none",
    },
    {
      key: "enabled_providers",
      label: "Enabled providers only",
      type: "array",
      file: "opencode.json",
      prismTouch: "none",
      description: "When set, only these providers load",
    },
    {
      key: "share",
      label: "Session share mode",
      type: "enum",
      enumValues: ["manual", "auto", "disabled"],
      file: "opencode.json",
      prismTouch: "none",
    },
    {
      key: "autoupdate",
      label: "Auto-update",
      type: "enum",
      enumValues: ["true", "false", "notify"],
      file: "opencode.json",
      prismTouch: "none",
      description: "boolean or 'notify' in schema",
    },
    {
      key: "username",
      label: "Display username",
      type: "string",
      file: "opencode.json",
      prismTouch: "none",
    },
    {
      key: "shell",
      label: "Default shell",
      type: "string",
      file: "opencode.json",
      prismTouch: "none",
    },
    {
      key: "logLevel",
      label: "Log level",
      type: "enum",
      enumValues: ["DEBUG", "INFO", "WARN", "ERROR"],
      file: "opencode.json",
      prismTouch: "none",
    },
    {
      key: "server",
      label: "Serve/web server",
      type: "object",
      file: "opencode.json",
      prismTouch: "none",
      description: "port, hostname, mdns, cors for opencode serve/web",
    },
    {
      key: "skills",
      label: "Skill path overrides",
      type: "object",
      file: "opencode.json",
      prismTouch: "none",
      description: "skills.paths / skills.urls — additional skill discovery",
    },
    {
      key: "instructions",
      label: "Extra instruction files",
      type: "array",
      file: "opencode.json",
      prismTouch: "none",
    },
    {
      key: "compaction",
      label: "Compaction settings",
      type: "object",
      file: "opencode.json",
      prismTouch: "none",
      description: "auto, prune, tail_turns, preserve_recent_tokens, reserved",
    },
    {
      key: "snapshot",
      label: "Filesystem snapshots",
      type: "boolean",
      file: "opencode.json",
      prismTouch: "none",
    },
    {
      key: "subagent_depth",
      label: "Max subagent depth",
      type: "number",
      file: "opencode.json",
      prismTouch: "none",
    },
    {
      key: "tools",
      label: "Tool enable map",
      type: "object",
      file: "opencode.json",
      prismTouch: "none",
      description: "Legacy boolean tool toggles; prefer permission",
    },
    {
      key: "formatter",
      label: "Formatter config",
      type: "object",
      file: "opencode.json",
      prismTouch: "none",
    },
    {
      key: "lsp",
      label: "LSP config",
      type: "object",
      file: "opencode.json",
      prismTouch: "none",
    },
    {
      key: "tool_output",
      label: "Tool output thresholds",
      type: "object",
      file: "opencode.json",
      prismTouch: "none",
      description: "max_lines, max_bytes before truncation",
    },
    {
      key: "experimental",
      label: "Experimental flags",
      type: "object",
      file: "opencode.json",
      prismTouch: "none",
    },
    {
      key: "attachment",
      label: "Attachment / image limits",
      type: "object",
      file: "opencode.json",
      prismTouch: "none",
    },
    {
      key: "command",
      label: "Inline command templates",
      type: "object",
      file: "opencode.json",
      prismTouch: "none",
      description: "Config-side commands; file-router commands live under commands/",
    },
    // --- TUI ---
    {
      key: "theme",
      label: "TUI theme",
      type: "string",
      file: "tui.json",
      prismTouch: "none",
    },
    {
      key: "scroll_speed",
      label: "TUI scroll speed",
      type: "number",
      file: "tui.json",
      prismTouch: "none",
    },
    {
      key: "keybinds",
      label: "TUI keybinds",
      type: "object",
      file: "tui.json",
      prismTouch: "none",
    },
    {
      key: "plugin",
      label: "TUI plugin array",
      type: "array",
      file: "tui.json",
      prismTouch: "none",
      description: "TUI-side plugins; separate from opencode.json plugin",
    },
  ],
  refresh: {
    lastResearched: "2026-08-11",
    procedure: [
      "Run `opencode --help` and `opencode run --help` (note --model, --agent, --format json, --dangerously-skip-permissions)",
      "Read ~/.config/opencode/opencode.json top-level keys (redact mcp.*.environment, provider.*.options.apiKey)",
      "Read ~/.config/opencode/tui.json",
      "Diff against https://opencode.ai/config.json Config properties",
      "Confirm Prism region ownership in src/compile/lowerers/opencode.ts (COMPILER_OWNED_KEYS, plugin array, permission ns deny)",
      "List plugins/prism-generated-* for install layout",
      "Update fields[] and lastResearched",
    ],
    sources: [
      "opencode --help",
      "opencode run --help",
      "~/.config/opencode/opencode.json",
      "~/.config/opencode/tui.json",
      "https://opencode.ai/config.json",
      "https://opencode.ai/tui.json",
      "https://opencode.ai/docs/config",
      "src/harnesses.ts",
      "src/lowerer-capabilities.ts",
      "src/compile/lowerers/opencode.ts",
      "src/workflow-opencode-worker.ts",
    ],
  },
  notes: [
    "Prism does not whole-file own opencode.json. Regions: agent.<name>.<compiler-key>, plugin[] members for prism-generated-*, permission.<ns>_* deny.",
    "Rules use marker regions in AGENTS.md (and alternative CLAUDE.md when present).",
    "Compile owns agents/<name>.md, skills/<orbit>/SKILL.md, and plugins/prism-generated-<plugin>/dist/server.mjs (native @opencode-ai/plugin API).",
    "Install-phase commands write commands/*.md directly; skills install to skills/.",
    "Workflow worker: PRISM_WORKFLOW_OPENCODE_BIN or `opencode`; args `run --dir --agent --format json [--model] [--dangerously-skip-permissions]`.",
    "MCP env blocks and provider apiKey are secrets — never display raw.",
    "Live top-level keys observed: $schema, agent, mcp, permission, plugin, small_model.",
  ],
};
