import type { HarnessCatalog } from "./types.js";

/**
 * OpenClaw settings catalogue — researched 2026-08-13 from live ~/.openclaw/openclaw.json,
 * zsh completions, harness registry, and lowerer capabilities.
 * Prism surface is skills-only (direct-file under skills/); no compile lowerer.
 */
export const openclawCatalog: HarnessCatalog = {
  harness: "openclaw",
  displayName: "OpenClaw",
  binaryNames: ["openclaw"],
  binaryEnvVars: [
    "OPENCLAW_STATE_DIR",
    "OPENCLAW_CONFIG_PATH",
    "OPENCLAW_CONTAINER",
    "OPENCLAW_GATEWAY_TOKEN",
  ],
  globalRoot: "~/.openclaw/",
  projectRoot: null,
  settingsFiles: [
    {
      path: "openclaw.json",
      format: "json",
      primary: true,
      note: "Primary gateway/agent/channel config; openclaw config schema|validate",
    },
    {
      path: "exec-approvals.json",
      format: "json",
      note: "Host exec-approvals socket + token — secrets",
    },
    {
      path: "update-check.json",
      format: "json",
      note: "Last update-check bookkeeping",
    },
    {
      path: "credentials/",
      format: "other",
      note: "Provider/channel credentials — never display",
    },
    {
      path: "identity/device-auth.json",
      format: "json",
      note: "Device auth — secrets",
    },
  ],
  scanDirs: ["skills", "agents", "extensions", "plugins", "hooks"],
  /** OpenClaw install is flat skills/<name>/ — no prism-generated- bundles today. */
  prismNamespaceMarkers: ["prism-generated-"],
  fields: [
    {
      key: "meta.lastTouchedVersion",
      label: "Last touched OpenClaw version",
      type: "string",
      file: "openclaw.json",
      prismTouch: "none",
    },
    {
      key: "meta.lastTouchedAt",
      label: "Last config touch time",
      type: "string",
      file: "openclaw.json",
      prismTouch: "none",
    },
    {
      key: "env.vars",
      label: "Config-level env vars",
      type: "object",
      file: "openclaw.json",
      prismTouch: "none",
      description: "e.g. OPENCLAW_AGENT_RUNTIME, OPENCLAW_AGENT_HARNESS_FALLBACK",
    },
    {
      key: "wizard.lastRunCommand",
      label: "Last wizard command",
      type: "string",
      file: "openclaw.json",
      prismTouch: "none",
    },
    {
      key: "auth.profiles",
      label: "Auth profiles",
      type: "object",
      file: "openclaw.json",
      prismTouch: "none",
      description: "Provider profile map (oauth/api_key/token modes) — redacted",
    },
    {
      key: "acp.enabled",
      label: "ACP enabled",
      type: "boolean",
      file: "openclaw.json",
      prismTouch: "none",
    },
    {
      key: "acp.backend",
      label: "ACP backend",
      type: "string",
      file: "openclaw.json",
      prismTouch: "none",
    },
    {
      key: "acp.defaultAgent",
      label: "ACP default agent",
      type: "string",
      file: "openclaw.json",
      prismTouch: "none",
    },
    {
      key: "acp.allowedAgents",
      label: "ACP allowed agents",
      type: "array",
      file: "openclaw.json",
      prismTouch: "none",
    },
    {
      key: "acp.maxConcurrentSessions",
      label: "ACP max concurrent sessions",
      type: "number",
      file: "openclaw.json",
      prismTouch: "none",
    },
    {
      key: "models.mode",
      label: "Models merge mode",
      type: "string",
      file: "openclaw.json",
      prismTouch: "none",
      description: "Live value: merge",
      cousin: "modelspace",
    },
    {
      key: "models.providers",
      label: "Model providers catalog",
      type: "object",
      file: "openclaw.json",
      prismTouch: "none",
      cousin: "modelspace",
    },
    {
      key: "agents.defaults.model.primary",
      label: "Default primary model",
      type: "string",
      file: "openclaw.json",
      prismTouch: "none",
      cousin: "model",
    },
    {
      key: "agents.defaults.model.fallbacks",
      label: "Default model fallbacks",
      type: "array",
      file: "openclaw.json",
      prismTouch: "none",
    },
    {
      key: "agents.defaults.agentRuntime.id",
      label: "Default agent runtime",
      type: "string",
      file: "openclaw.json",
      prismTouch: "none",
      description: "e.g. codex harness runtime id",
    },
    {
      key: "agents.defaults.thinkingDefault",
      label: "Default thinking level",
      type: "string",
      file: "openclaw.json",
      prismTouch: "none",
      cousin: "effort",
    },
    {
      key: "agents.defaults.reasoningDefault",
      label: "Default reasoning",
      type: "string",
      file: "openclaw.json",
      prismTouch: "none",
    },
    {
      key: "agents.defaults.workspace",
      label: "Default workspace path",
      type: "string",
      file: "openclaw.json",
      prismTouch: "none",
    },
    {
      key: "agents.defaults.memorySearch.model",
      label: "Memory search embedding model",
      type: "string",
      file: "openclaw.json",
      prismTouch: "none",
      description:
        "Live installs still use agents.defaults.memorySearch.* (this path). Current docs use memory.search.model.",
    },
    {
      key: "agents.defaults.memorySearch.enabled",
      label: "Memory search enabled (legacy path)",
      type: "boolean",
      file: "openclaw.json",
      prismTouch: "none",
      description:
        "Dual-read with memory.search.enabled. Live disk may only set memorySearch.model under agents.defaults.",
    },
    {
      key: "memory.search.enabled",
      label: "Memory search enabled",
      type: "boolean",
      file: "openclaw.json",
      prismTouch: "none",
      description:
        "Current-docs path (default true). Live installs may still only have agents.defaults.memorySearch.*.",
    },
    {
      key: "memory.search.provider",
      label: "Memory search provider",
      type: "string",
      file: "openclaw.json",
      prismTouch: "none",
      description:
        "Current-docs path (default openai). Live/legacy: agents.defaults.memorySearch.provider. e.g. openai, gemini, voyage, local, ollama.",
    },
    {
      key: "plugins.entries.memory-core.config.dreaming.enabled",
      label: "Memory-core dreaming",
      type: "boolean",
      file: "openclaw.json",
      prismTouch: "none",
      description:
        "Not under memory.search. Live sample: plugins.entries.memory-core.config.dreaming.{enabled,frequency}.",
    },
    {
      key: "agents.defaults.heartbeat.every",
      label: "Default heartbeat interval",
      type: "string",
      file: "openclaw.json",
      prismTouch: "none",
      description: "Duration string; 0m disables",
    },
    {
      key: "agents.defaults.sandbox.mode",
      label: "Default sandbox mode",
      type: "string",
      file: "openclaw.json",
      prismTouch: "none",
    },
    {
      key: "agents.defaults.maxConcurrent",
      label: "Default max concurrent agents",
      type: "number",
      file: "openclaw.json",
      prismTouch: "none",
    },
    {
      key: "agents.defaults.subagents.maxConcurrent",
      label: "Default max concurrent subagents",
      type: "number",
      file: "openclaw.json",
      prismTouch: "none",
    },
    {
      key: "agents.list",
      label: "Agent list",
      type: "array",
      file: "openclaw.json",
      prismTouch: "none",
      description:
        "Native OpenClaw multi-agent entries (id/name/workspace/model); not Prism compile agents",
    },
    {
      key: "tools.profile",
      label: "Tools profile",
      type: "string",
      file: "openclaw.json",
      prismTouch: "none",
    },
    {
      key: "tools.web.search.enabled",
      label: "Web search enabled",
      type: "boolean",
      file: "openclaw.json",
      prismTouch: "none",
    },
    {
      key: "tools.web.search.provider",
      label: "Web search provider",
      type: "string",
      file: "openclaw.json",
      prismTouch: "none",
    },
    {
      key: "tools.exec.security",
      label: "Exec security level",
      type: "string",
      file: "openclaw.json",
      prismTouch: "none",
      cousin: "permission-posture",
    },
    {
      key: "tools.exec.ask",
      label: "Exec ask mode",
      type: "string",
      file: "openclaw.json",
      prismTouch: "none",
    },
    {
      key: "tools.exec.applyPatch.workspaceOnly",
      label: "Exec applyPatch workspace-only",
      type: "boolean",
      file: "openclaw.json",
      prismTouch: "none",
    },
    {
      key: "tools.fs.workspaceOnly",
      label: "Filesystem workspace-only",
      type: "boolean",
      file: "openclaw.json",
      prismTouch: "none",
    },
    {
      key: "bindings",
      label: "Channel route bindings",
      type: "array",
      file: "openclaw.json",
      prismTouch: "none",
      description: "route entries mapping channel/account/peer → agentId",
    },
    {
      key: "commands.native",
      label: "Native commands mode",
      type: "string",
      file: "openclaw.json",
      prismTouch: "none",
    },
    {
      key: "commands.nativeSkills",
      label: "Native skills commands mode",
      type: "string",
      file: "openclaw.json",
      prismTouch: "none",
    },
    {
      key: "commands.restart",
      label: "Commands restart allowed",
      type: "boolean",
      file: "openclaw.json",
      prismTouch: "none",
    },
    {
      key: "commands.ownerAllowFrom",
      label: "Owner allow-from",
      type: "array",
      file: "openclaw.json",
      prismTouch: "none",
    },
    {
      key: "session.dmScope",
      label: "DM session scope",
      type: "string",
      file: "openclaw.json",
      prismTouch: "none",
    },
    {
      key: "hooks.internal.enabled",
      label: "Internal hooks enabled",
      type: "boolean",
      file: "openclaw.json",
      prismTouch: "none",
      description: "Native OpenClaw internal hooks; Prism has no hook lowerer for openclaw",
    },
    {
      key: "hooks.internal.entries",
      label: "Internal hook entries",
      type: "object",
      file: "openclaw.json",
      prismTouch: "none",
    },
    {
      key: "channels",
      label: "Channels config",
      type: "object",
      file: "openclaw.json",
      prismTouch: "none",
      description: "Per-channel adapters (e.g. matrix.accounts) — may embed secrets",
    },
    {
      key: "channels.matrix.enabled",
      label: "Matrix channel enabled",
      type: "boolean",
      file: "openclaw.json",
      prismTouch: "none",
    },
    {
      key: "gateway.port",
      label: "Gateway port",
      type: "number",
      file: "openclaw.json",
      prismTouch: "none",
    },
    {
      key: "gateway.mode",
      label: "Gateway mode",
      type: "string",
      file: "openclaw.json",
      prismTouch: "none",
    },
    {
      key: "gateway.bind",
      label: "Gateway bind",
      type: "enum",
      enumValues: ["loopback", "tailnet", "lan", "auto", "custom"],
      file: "openclaw.json",
      prismTouch: "none",
    },
    {
      key: "gateway.auth.mode",
      label: "Gateway auth mode",
      type: "enum",
      enumValues: ["token", "password"],
      file: "openclaw.json",
      prismTouch: "none",
    },
    {
      key: "gateway.auth.token",
      label: "Gateway auth token",
      type: "secret",
      file: "openclaw.json",
      prismTouch: "none",
    },
    {
      key: "gateway.controlUi.allowedOrigins",
      label: "Control UI allowed origins",
      type: "array",
      file: "openclaw.json",
      prismTouch: "none",
    },
    {
      key: "gateway.tailscale.mode",
      label: "Gateway Tailscale mode",
      type: "string",
      file: "openclaw.json",
      prismTouch: "none",
    },
    {
      key: "gateway.nodes.denyCommands",
      label: "Gateway node deny commands",
      type: "array",
      file: "openclaw.json",
      prismTouch: "none",
    },
    {
      key: "plugins.entries",
      label: "Plugin entries",
      type: "object",
      file: "openclaw.json",
      prismTouch: "none",
      description:
        "Native plugin enable/config map; may embed apiKeys — Prism does not manage plugin bundles",
    },
    {
      key: "messages.ackReactionScope",
      label: "Ack reaction scope",
      type: "string",
      file: "openclaw.json",
      prismTouch: "none",
    },
    {
      key: "messages.groupChat.visibleReplies",
      label: "Group chat visible replies",
      type: "string",
      file: "openclaw.json",
      prismTouch: "none",
    },
    {
      key: "skills.entries",
      label: "Skill enable map",
      type: "object",
      file: "openclaw.json",
      prismTouch: "none",
      description:
        "Per-skill enabled flags in openclaw.json; install files live under skills/ (Prism owns skill folders only)",
    },
    {
      key: "version",
      label: "Exec-approvals schema version",
      type: "number",
      file: "exec-approvals.json",
      prismTouch: "none",
    },
    {
      key: "socket.path",
      label: "Exec-approvals socket path",
      type: "string",
      file: "exec-approvals.json",
      prismTouch: "none",
    },
    {
      key: "socket.token",
      label: "Exec-approvals socket token",
      type: "secret",
      file: "exec-approvals.json",
      prismTouch: "none",
    },
  ],
  refresh: {
    lastResearched: "2026-08-13",
    procedure: [
      "Run `openclaw --help` and `openclaw config schema` (or schema subcommand)",
      "Read ~/.openclaw/openclaw.json top-level keys (redact gateway.auth.token, plugin apiKeys, credentials/)",
      "Read ~/.openclaw/exec-approvals.json keys (redact socket.token)",
      "Confirm Prism still only installs skills/ via refresh file-router (no openclaw lowerer)",
      "List skills/ for inventory shape; note flat skill dirs vs prism-generated- bundles",
      "Cross-check src/harnesses.ts openclaw entry and src/lowerer-capabilities.ts surfaces",
      "Update fields[] and lastResearched",
    ],
    sources: [
      "openclaw --help",
      "openclaw config schema",
      "openclaw config validate",
      "openclaw doctor",
      "openclaw skills",
      "openclaw plugins",
      "~/.openclaw/openclaw.json",
      "https://docs.openclaw.ai/reference/memory-config",
      "https://docs.openclaw.ai/concepts/memory",
      "~/.openclaw/exec-approvals.json",
      "~/.openclaw/completions/openclaw.zsh",
      "src/harnesses.ts",
      "src/lowerer-capabilities.ts",
      "src/refresh.ts (skills install)",
    ],
  },
  notes: [
    "Prism is skills-only: shared + harness/openclaw overlays install into ~/.openclaw/skills/<name>/ as direct-file Agent Skill folders.",
    "No compile lowerer (src/compile/lowerers/ has no openclaw.ts). Hooks, agents, commands, tools, plugin bundles, and openclaw.json are unsupported for Prism writes.",
    "harnesses.ts lists agentsDir and supportsAgents:true for native OpenClaw agent state dirs; lowerer-capabilities.agents is unsupported — Prism does not compile agents into OpenClaw.",
    "projectConfigPath is null — global root only (~/.openclaw/). Profiles use --profile / OPENCLAW_STATE_DIR → ~/.openclaw-<name>.",
    "openclaw.json is user-owned whole file; Prism never patches regions in it (prismTouch=none for all settings keys).",
    "Secrets live in openclaw.json (gateway.auth.token, plugins.*.config.apiKey), credentials/, identity/, exec-approvals.json — always redact.",
    "workflowWorker: false — OpenClaw is not a Prism workflow harness worker.",
    "claw-harness preset companion of hermes; inventory doctor groups only skills.",
    "No project root. Memory is per-agent workspace Markdown: MEMORY.md + memory/*.md (read-only in this catalogue). Dual-read: live agents.defaults.memorySearch.* vs current-docs memory.search.*.",
  ],
};
