import type { HarnessCatalog } from "./types.js";

/** Pi settings catalogue — researched 2026-08-11 from live settings.json, lowerer, and docs. */
export const piCatalog: HarnessCatalog = {
  harness: "pi",
  displayName: "Pi",
  binaryNames: ["pi"],
  globalRoot: "~/.pi/agent/",
  projectRoot: ".pi/",
  settingsFiles: [
    { path: "settings.json", format: "json", primary: true },
    { path: "auth.json", format: "json", note: "provider OAuth/API credentials — secrets, never display" },
    {
      path: "models-store.json",
      format: "json",
      note: "installed/custom model catalog cache (live install)",
    },
    {
      path: "models.json",
      format: "json",
      note: "optional user custom providers/models (docs); may be absent",
    },
    { path: "trust.json", format: "json", note: "trusted project paths map" },
  ],
  scanDirs: ["packages", "skills", "sessions", "agents"],
  prismNamespaceMarkers: ["prism-generated-"],
  fields: [
    {
      key: "packages",
      label: "Packages",
      type: "array",
      file: "settings.json",
      prismTouch: "region",
      description:
        "Local/npm/git package paths. Prism patches array members ./packages/prism-generated-<plugin> via DesiredRegion (json-array-member).",
    },
    {
      key: "defaultProvider",
      label: "Default provider",
      type: "string",
      file: "settings.json",
      prismTouch: "none",
      cousin: "modelspace",
      description: 'e.g. "anthropic", "openai", "opencode"',
    },
    {
      key: "defaultModel",
      label: "Default model",
      type: "string",
      file: "settings.json",
      prismTouch: "none",
      cousin: "modelspace",
    },
    {
      key: "defaultThinkingLevel",
      label: "Default thinking level",
      type: "enum",
      enumValues: ["off", "minimal", "low", "medium", "high", "xhigh"],
      file: "settings.json",
      prismTouch: "none",
      cousin: "effort",
      description: "Documented setting; agent frontmatter may also set thinking",
    },
    {
      key: "thinking",
      label: "Thinking (alias)",
      type: "string",
      file: "settings.json",
      prismTouch: "none",
      cousin: "effort",
      description: "Some docs show top-level thinking; prefer defaultThinkingLevel when both exist",
    },
    {
      key: "hideThinkingBlock",
      label: "Hide thinking block",
      type: "boolean",
      file: "settings.json",
      prismTouch: "none",
    },
    {
      key: "theme",
      label: "Theme",
      type: "string",
      file: "settings.json",
      prismTouch: "none",
    },
    {
      key: "compaction",
      label: "Compaction",
      type: "object",
      file: "settings.json",
      prismTouch: "none",
      description: "Session compaction config (enabled, keepRecentTokens / keepRecentTurns)",
    },
    {
      key: "compaction.enabled",
      label: "Compaction enabled",
      type: "boolean",
      file: "settings.json",
      prismTouch: "none",
    },
    {
      key: "enabledModels",
      label: "Enabled models",
      type: "array",
      file: "settings.json",
      prismTouch: "none",
      description: "Optional favorites filter (provider/model id strings)",
    },
    {
      key: "quietStartup",
      label: "Quiet startup",
      type: "boolean",
      file: "settings.json",
      prismTouch: "none",
    },
    {
      key: "lastChangelogVersion",
      label: "Last changelog version",
      type: "string",
      file: "settings.json",
      prismTouch: "none",
      description: "UI bookkeeping; not a user preference to edit",
    },
  ],
  refresh: {
    lastResearched: "2026-08-11",
    procedure: [
      "Run `pi --help` and `pi install --help` if present; note package install surface",
      "Read ~/.pi/agent/settings.json top-level keys (redact auth.json entirely)",
      "Compare https://github.com/badlogic/pi-mono/blob/main/packages/coding-agent/docs/settings.md (or earendil-works fork mirror)",
      "Confirm Prism still patches settings.json#packages as json-array-member in src/compile/lowerers/pi.ts",
      "List packages/prism-generated-* and ~/.pi/agents/*.md for install layout",
      "Update fields[] and lastResearched",
    ],
    sources: [
      "pi --help",
      "~/.pi/agent/settings.json",
      "~/.pi/agent/packages/",
      "~/.pi/agents/",
      "https://github.com/badlogic/pi-mono/blob/main/packages/coding-agent/docs/settings.md",
      "src/harnesses.ts",
      "src/lowerer-capabilities.ts",
      "src/compile/lowerers/pi.ts",
      "src/doctor.ts (scanDirs for pi)",
    ],
  },
  notes: [
    "Global root is ~/.pi/agent/ (settings + packages + skills + sessions). Compiled agents lower to sibling ~/.pi/agents/ (global) or .pi/agents/ (project) — not under agent/.",
    "Prism registers generated packages only: settings.json#packages array members ./packages/prism-generated-<plugin>. Other keys are user-owned (prismTouch none).",
    "Generated package layout: packages/prism-generated-<plugin>/{package.json, extensions/, skills/, prompts/, hooks/}. package.json pi.{extensions,skills,prompts} declares discovery.",
    "Rules lower as before_agent_start context in extensions/prism-extension.js — not AGENTS.md regions.",
    "workflowWorker is false for pi; no PRISM_WORKFLOW_PI_BIN in workflow harness detection.",
    "auth.json holds OAuth tokens — never surface values. trust.json maps absolute project paths to boolean trust.",
    "Live sample keys (2026-08-11): packages, lastChangelogVersion, theme, defaultProvider, defaultModel.",
  ],
};
