export const GENERATED_HOOK_RUNTIME = `// GENERATED by prism — do not edit.
const success = (value) => ({ _tag: "Success", success: value });
const failure = (message) => ({ _tag: "Failure", failure: message });
const isObject = (value) => value !== null && typeof value === "object" && !Array.isArray(value);

const isValidSession = (session) => {
  if (!isObject(session)) return false;
  if (session.id !== undefined && typeof session.id !== "string") return false;
  if (session.transcriptPath !== undefined && typeof session.transcriptPath !== "string") return false;
  return true;
};

const isValidNative = (native) => {
  return isObject(native);
};

const isValidCwd = (cwd) => cwd === undefined || typeof cwd === "string";

const isValidTarget = (target) => {
  return isObject(target) && typeof target.harness === "string" && typeof target.nativeEvent === "string";
};

const isValidTool = (tool) => {
  if (!isObject(tool)) return false;
  if (typeof tool.name !== "string") return false;
  if (tool.logical !== undefined && typeof tool.logical !== "string") return false;
  return true;
};

export const decodeNativeHookPayloadForEvent = (event, payload) => {
  if (!isObject(payload)) return failure("native hook payload must be an object");
  if (!isValidTarget(payload.target)) return failure("native hook payload target is invalid");
  if (!isValidCwd(payload.cwd)) return failure("native hook payload cwd is invalid");

  if (payload.session !== undefined && !isValidSession(payload.session)) {
    return failure("native hook payload session is invalid");
  }
  if (payload.native !== undefined && !isValidNative(payload.native)) {
    return failure("native hook payload native context is invalid");
  }

  const target = payload.target;
  const session = payload.session;
  const native = payload.native;
  const cwd = payload.cwd;

  if (event === "tool.before") {
    if (!isValidTool(payload.tool)) return failure("tool.before payload tool is invalid");
    return success({
      event,
      target,
      cwd,
      session,
      native,
      tool: {
        logical: payload.tool.logical,
        nativeName: payload.tool.name,
        input: payload.tool.input
      }
    });
  }
  if (event === "tool.after") {
    if (!isValidTool(payload.tool)) return failure("tool.after payload tool is invalid");
    if (payload.tool.success !== undefined && typeof payload.tool.success !== "boolean") {
      return failure("tool.after payload tool success is invalid");
    }
    return success({
      event,
      target,
      cwd,
      session,
      native,
      tool: {
        logical: payload.tool.logical,
        nativeName: payload.tool.name,
        input: payload.tool.input,
        output: payload.tool.output,
        success: payload.tool.success
      }
    });
  }
  if (event === "tool.failure") {
    if (!isValidTool(payload.tool)) return failure("tool.failure payload tool is invalid");
    return success({
      event,
      target,
      cwd,
      session,
      native,
      tool: {
        logical: payload.tool.logical,
        nativeName: payload.tool.name,
        input: payload.tool.input,
        error: payload.tool.error
      }
    });
  }
  if (event === "prompt.submit") {
    if (typeof payload.prompt !== "string") return failure("prompt.submit payload prompt is invalid");
    return success({ event, target, cwd, session, native, prompt: payload.prompt });
  }
  if (event === "permission.request") {
    if (payload.tool !== undefined && !isValidTool(payload.tool)) {
      return failure("permission.request payload tool is invalid");
    }
    const tool = payload.tool ? {
      logical: payload.tool.logical,
      nativeName: payload.tool.name,
      input: payload.tool.input
    } : undefined;
    return success({ event, target, cwd, session, native, tool });
  }
  if (event === "session.start") {
    if (session === undefined || !isValidSession(session)) return failure("session.start payload session is invalid");
    return success({ event, target, cwd, session, native });
  }
  if (event === "session.end") {
    if (session === undefined || !isValidSession(session)) return failure("session.end payload session is invalid");
    if (payload.reason !== undefined && typeof payload.reason !== "string") return failure("session.end payload reason is invalid");
    return success({ event, target, cwd, session, reason: payload.reason, native });
  }
  if (event === "stop") {
    if (payload.stopHookActive !== undefined && typeof payload.stopHookActive !== "boolean") {
      return failure("stop payload stopHookActive is invalid");
    }
    return success({ event, target, cwd, session, native, stopHookActive: payload.stopHookActive });
  }
  if (event === "subagent.start" || event === "subagent.stop") {
    if (payload.subagent !== undefined) {
      if (!isObject(payload.subagent)) return failure(event + " payload subagent is invalid");
      if (payload.subagent.id !== undefined && typeof payload.subagent.id !== "string") {
        return failure(event + " payload subagent id is invalid");
      }
      if (payload.subagent.type !== undefined && typeof payload.subagent.type !== "string") {
        return failure(event + " payload subagent type is invalid");
      }
    }
    const subagent = payload.subagent ? {
      id: payload.subagent.id,
      type: payload.subagent.type
    } : undefined;
    return success({ event, target, cwd, session, native, subagent });
  }
  if (event === "compact.before" || event === "compact.after") {
    if (payload.trigger !== undefined && typeof payload.trigger !== "string") {
      return failure(event + " payload trigger is invalid");
    }
    return success({ event, target, cwd, session, native, trigger: payload.trigger });
  }
  if (event === "notification") {
    if (payload.message !== undefined && typeof payload.message !== "string") {
      return failure("notification payload message is invalid");
    }
    if (payload.kind !== undefined && typeof payload.kind !== "string") {
      return failure("notification payload kind is invalid");
    }
    return success({ event, target, cwd, session, native, message: payload.message, kind: payload.kind });
  }
  return failure("unknown hook event");
};

export const decodeHookResultForEvent = (event, result) => {
  if (!isObject(result)) return failure("hook result must be an object");

  if (event === "tool.before") {
    if (result.decision === "continue") {
      if (result.systemMessage !== undefined && typeof result.systemMessage !== "string") return failure("systemMessage must be a string");
      if (result.additionalContext !== undefined && typeof result.additionalContext !== "string") return failure("additionalContext must be a string");
      const res = { decision: "continue" };
      if ("updatedInput" in result) res.updatedInput = result.updatedInput;
      if (result.systemMessage !== undefined) res.systemMessage = result.systemMessage;
      if (result.additionalContext !== undefined) res.additionalContext = result.additionalContext;
      return success(res);
    }
    if (result.decision === "block") {
      if (typeof result.message !== "string") return failure("block message must be a string");
      if (result.systemMessage !== undefined && typeof result.systemMessage !== "string") return failure("systemMessage must be a string");
      const res = { decision: "block", message: result.message };
      if (result.systemMessage !== undefined) res.systemMessage = result.systemMessage;
      return success(res);
    }
    return failure("invalid hook result for tool.before");
  }

  if (event === "tool.after") {
    if (result.decision === "continue") {
      if (result.systemMessage !== undefined && typeof result.systemMessage !== "string") return failure("systemMessage must be a string");
      if (result.additionalContext !== undefined && typeof result.additionalContext !== "string") return failure("additionalContext must be a string");
      const res = { decision: "continue" };
      if ("updatedOutput" in result) res.updatedOutput = result.updatedOutput;
      if (result.systemMessage !== undefined) res.systemMessage = result.systemMessage;
      if (result.additionalContext !== undefined) res.additionalContext = result.additionalContext;
      return success(res);
    }
    return failure("invalid hook result for tool.after");
  }

  if (event === "tool.failure" || event === "session.start" || event === "session.end" || event === "subagent.start" || event === "compact.after") {
    if (result.decision === "continue") {
      if (result.systemMessage !== undefined && typeof result.systemMessage !== "string") return failure("systemMessage must be a string");
      if (result.additionalContext !== undefined && typeof result.additionalContext !== "string") return failure("additionalContext must be a string");
      const res = { decision: "continue" };
      if (result.systemMessage !== undefined) res.systemMessage = result.systemMessage;
      if (result.additionalContext !== undefined) res.additionalContext = result.additionalContext;
      return success(res);
    }
    return failure("invalid hook result for " + event);
  }

  if (event === "prompt.submit" || event === "subagent.stop" || event === "compact.before") {
    if (result.decision === "continue") {
      if (result.systemMessage !== undefined && typeof result.systemMessage !== "string") return failure("systemMessage must be a string");
      if (result.additionalContext !== undefined && typeof result.additionalContext !== "string") return failure("additionalContext must be a string");
      const res = { decision: "continue" };
      if (result.systemMessage !== undefined) res.systemMessage = result.systemMessage;
      if (result.additionalContext !== undefined) res.additionalContext = result.additionalContext;
      return success(res);
    }
    if (result.decision === "block") {
      if (typeof result.message !== "string") return failure("block message must be a string");
      return success({ decision: "block", message: result.message });
    }
    return failure("invalid hook result for " + event);
  }

  if (event === "permission.request") {
    if (result.decision === "continue") {
      if (result.systemMessage !== undefined && typeof result.systemMessage !== "string") return failure("systemMessage must be a string");
      if (result.additionalContext !== undefined && typeof result.additionalContext !== "string") return failure("additionalContext must be a string");
      const res = { decision: "continue" };
      if (result.systemMessage !== undefined) res.systemMessage = result.systemMessage;
      if (result.additionalContext !== undefined) res.additionalContext = result.additionalContext;
      return success(res);
    }
    if (result.decision === "allow") {
      if (result.systemMessage !== undefined && typeof result.systemMessage !== "string") return failure("systemMessage must be a string");
      const res = { decision: "allow" };
      if ("updatedInput" in result) res.updatedInput = result.updatedInput;
      if (result.systemMessage !== undefined) res.systemMessage = result.systemMessage;
      return success(res);
    }
    if (result.decision === "ask") {
      if (result.systemMessage !== undefined && typeof result.systemMessage !== "string") return failure("systemMessage must be a string");
      const res = { decision: "ask" };
      if (result.systemMessage !== undefined) res.systemMessage = result.systemMessage;
      return success(res);
    }
    if (result.decision === "block") {
      if (typeof result.message !== "string") return failure("block message must be a string");
      return success({ decision: "block", message: result.message });
    }
    return failure("invalid hook result for permission.request");
  }

  if (event === "stop") {
    if (result.decision === "continue") {
      if (result.systemMessage !== undefined && typeof result.systemMessage !== "string") return failure("systemMessage must be a string");
      const res = { decision: "continue" };
      if (result.systemMessage !== undefined) res.systemMessage = result.systemMessage;
      return success(res);
    }
    if (result.decision === "block") {
      if (typeof result.message !== "string") return failure("block message must be a string");
      return success({ decision: "block", message: result.message });
    }
    return failure("invalid hook result for stop");
  }

  if (event === "notification") {
    if (result.decision === "continue") {
      if (result.systemMessage !== undefined && typeof result.systemMessage !== "string") return failure("systemMessage must be a string");
      const res = { decision: "continue" };
      if (result.systemMessage !== undefined) res.systemMessage = result.systemMessage;
      return success(res);
    }
    return failure("invalid hook result for notification");
  }

  return failure("invalid hook result for " + event);
};
`;
