export const GENERATED_HOOK_RUNTIME = `// GENERATED by prism — do not edit.
const right = (value) => ({ _tag: "Right", right: value });
const left = (message) => ({ _tag: "Left", left: message });
const isObject = (value) => value !== null && typeof value === "object";
const decodeTarget = (payload) => isObject(payload?.target) && typeof payload.target.harness === "string" && typeof payload.target.nativeEvent === "string"
  ? payload.target
  : undefined;
const decodeSession = (payload) => payload?.session === undefined || isObject(payload.session)
  ? payload.session
  : undefined;
const decodeNative = (payload) => payload?.native === undefined || isObject(payload.native)
  ? payload.native
  : undefined;
export const decodeNativeHookPayloadForEvent = (event, payload) => {
  if (!isObject(payload)) return left("native hook payload must be an object");
  const target = decodeTarget(payload);
  if (!target) return left("native hook payload target is invalid");
  const session = decodeSession(payload);
  if (payload.session !== undefined && !session) return left("native hook payload session is invalid");
  const native = decodeNative(payload);
  if (payload.native !== undefined && !native) return left("native hook payload native context is invalid");
  if (event === "tool.before") {
    if (!isObject(payload.tool) || typeof payload.tool.name !== "string") return left("tool.before payload tool is invalid");
    return right({ event, target, cwd: payload.cwd, session, native, tool: { logical: payload.tool.logical, nativeName: payload.tool.name, input: payload.tool.input } });
  }
  if (event === "tool.after") {
    if (!isObject(payload.tool) || typeof payload.tool.name !== "string") return left("tool.after payload tool is invalid");
    return right({ event, target, cwd: payload.cwd, session, native, tool: { logical: payload.tool.logical, nativeName: payload.tool.name, input: payload.tool.input, output: payload.tool.output, success: payload.tool.success } });
  }
  if (event === "prompt.submit") {
    if (typeof payload.prompt !== "string") return left("prompt.submit payload prompt is invalid");
    return right({ event, target, cwd: payload.cwd, session, native, prompt: payload.prompt });
  }
  if (event === "permission.request") {
    const tool = payload.tool === undefined ? undefined : payload.tool;
    if (tool !== undefined && (!isObject(tool) || typeof tool.name !== "string")) return left("permission.request payload tool is invalid");
    return right({ event, target, cwd: payload.cwd, session, native, tool: tool ? { logical: tool.logical, nativeName: tool.name, input: tool.input } : undefined });
  }
  if (event === "session.start") {
    if (!isObject(session)) return left("session.start payload session is invalid");
    return right({ event, target, cwd: payload.cwd, session, native });
  }
  if (event === "session.end") {
    if (!isObject(session)) return left("session.end payload session is invalid");
    return right({ event, target, cwd: payload.cwd, session, reason: payload.reason, native });
  }
  return left("unknown hook event");
};
export const decodeHookResultForEvent = (event, result) => {
  if (!isObject(result)) return left("hook result must be an object");
  if (event === "tool.before" && result.decision === "block" && typeof result.message === "string") return right(result);
  if (event === "permission.request" && result.decision === "block" && typeof result.message === "string") return right(result);
  if (event === "permission.request" && result.decision === "allow") return right({
    decision: "allow",
    systemMessage: typeof result.systemMessage === "string" ? result.systemMessage : undefined,
  });
  if (result.decision === "continue") return right({
    decision: "continue",
    systemMessage: typeof result.systemMessage === "string" ? result.systemMessage : undefined,
    additionalContext: typeof result.additionalContext === "string" ? result.additionalContext : undefined,
  });
  return left("invalid hook result for " + event);
};
`;
