import { join } from "node:path";
import type { CompileManifest, CompileManifestAgent } from "./compile-manifest.js";
import type { DesiredRoot } from "../sync/desired.js";
import { collectPluginRegistries, type PluginRegistry } from "./registry.js";

export const WORKFLOW_REFS_HARNESS = "prism-workflows";

export const workflowRefsRoot = (projectPath: string): string => join(projectPath, ".prism");

export const workflowAgentsPath = (projectPath: string): string =>
  join(workflowRefsRoot(projectPath), "generated", "workflows", "agents.ts");

const camelKey = (value: string): string => {
  const parts = value
    .split(/[^A-Za-z0-9]+/u)
    .filter((part) => part.length > 0);
  const [first, ...rest] = parts;
  if (!first) return "agent";
  const normalizedFirst = first[0]!.toLowerCase() + first.slice(1);
  return [
    normalizedFirst,
    ...rest.map((part) => part[0]!.toUpperCase() + part.slice(1)),
  ].join("");
};

const pluginNames = (manifest: CompileManifest): string[] =>
  [...new Set(Object.values(manifest.agents).map((agent) => agent.plugin))].sort();

const pluginAgents = (
  manifest: CompileManifest,
  pluginName: string,
): CompileManifestAgent[] =>
  Object.values(manifest.agents)
    .filter((agent) => agent.plugin === pluginName)
    .sort((left, right) => left.name.localeCompare(right.name));

const agentSourcePath = (
  registries: ReadonlyMap<string, PluginRegistry>,
  agent: CompileManifestAgent,
): string =>
  registries.get(agent.plugin)?.agents.get(agent.name)?.sourcePath ?? "";

const agentInstalls = (agent: CompileManifestAgent): string[] =>
  Object.keys(agent.composed.perTarget).sort();

const renderAgentRef = (options: {
  readonly registries: ReadonlyMap<string, PluginRegistry>;
  readonly agent: CompileManifestAgent;
}): string => {
  const sourcePath = agentSourcePath(options.registries, options.agent);
  const modelBindings = options.agent.composed.modelBindings;
  const model =
    modelBindings.modelspace || modelBindings.profile
      ? `,
      model: ${JSON.stringify(modelBindings)}`
      : "";

  return `{
      kind: "agent-ref",
      plugin: ${JSON.stringify(options.agent.plugin)},
      name: ${JSON.stringify(options.agent.name)},
      description: ${JSON.stringify(options.agent.description)},
      sourcePath: ${JSON.stringify(sourcePath)},
      sourceHash: ${JSON.stringify(options.agent.sourceHash)},
      manifestHash: ${JSON.stringify(options.agent.manifestHash)}${model},
      installs: ${JSON.stringify(agentInstalls(options.agent))}
    }`;
};

const renderAgentsNamespace = (options: {
  readonly registries: ReadonlyMap<string, PluginRegistry>;
  readonly manifest: CompileManifest;
  readonly pluginName: string;
}): string => {
  const entries = pluginAgents(options.manifest, options.pluginName).map((agent) =>
    `    ${JSON.stringify(camelKey(agent.name))}: ${renderAgentRef({ registries: options.registries, agent })}`,
  );
  return entries.length > 0 ? entries.join(",\n") : "";
};

export const renderWorkflowAgentsModule = (options: {
  readonly registry: PluginRegistry;
  readonly manifest: CompileManifest;
}): string => {
  const registries = collectPluginRegistries(options.registry);
  const namespaces = pluginNames(options.manifest).map((pluginName) => {
    const pluginKey = camelKey(pluginName);
    const body = renderAgentsNamespace({
      registries,
      manifest: options.manifest,
      pluginName,
    });
    return `  ${JSON.stringify(pluginKey)}: {
${body}
  }`;
  });

  return `/**
 * Generated by Prism. Do not edit.
 * Source: compile manifest ${options.manifest.manifestHash}
 */

export interface WorkflowModelRef {
  readonly modelspace?: string;
  readonly profile?: string;
}

export interface WorkflowAgentRef {
  readonly kind: "agent-ref";
  readonly plugin: string;
  readonly name: string;
  readonly description: string;
  readonly sourcePath: string;
  readonly sourceHash: string;
  readonly manifestHash: string;
  readonly model?: WorkflowModelRef;
  readonly installs: ReadonlyArray<string>;
}

export const agents = {
${namespaces.join(",\n")}
} as const satisfies Record<string, Record<string, WorkflowAgentRef>>;
`;
};

export const planWorkflowRefsEmit = (options: {
  readonly projectPath: string;
  readonly registry: PluginRegistry;
  readonly manifest: CompileManifest;
}): DesiredRoot => {
  const root = workflowRefsRoot(options.projectPath);
  return {
    harness: WORKFLOW_REFS_HARNESS,
    root,
    files: [
      {
        targetPath: workflowAgentsPath(options.projectPath),
        content: renderWorkflowAgentsModule({
          registry: options.registry,
          manifest: options.manifest,
        }),
        plugin: WORKFLOW_REFS_HARNESS,
      },
    ],
    regions: [],
  };
};
