import { describe, expect, test } from "bun:test";
import { emptyCompileManifest } from "./compile-manifest.js";
import { buildCompileManifestForTarget } from "./compile-manifest.js";
import type { AgentCacheDescriptor } from "./cache.js";
import type { ComposedAgent } from "./compose.js";
import { emptyRegistry } from "./registry.js";
import { Agent } from "./sources.js";
import {
  planWorkflowRefsEmit,
  renderWorkflowAgentsModule,
  workflowAgentsPath,
  workflowRefsRoot,
  WORKFLOW_REFS_HARNESS,
} from "./workflow-refs-emitter.js";

const registry = () => {
  const registry = emptyRegistry("/tmp/forge", "forge", "1.0.0");
  registry.agents.set("codebase-archeologist", new Agent({
    name: "codebase-archeologist",
    sourcePath: "/tmp/forge/agents/codebase-archeologist.agent.ts",
    description: "Maps legacy strata",
    identity: "builder",
    traits: [],
    access: { tools: [], toolGroups: [], skills: [] },
    skills: [],
    targets: {},
  }));
  return registry;
};

const descriptor: AgentCacheDescriptor = {
  key: "codebase-archeologist-key",
  sourceHash: "a".repeat(64),
  contextHash: "context",
  inputs: [{ plugin: "forge", path: "agents/codebase-archeologist.agent.ts", contentHash: "a".repeat(64) }],
};

const composed: ComposedAgent = {
  name: "codebase-archeologist",
  description: "Maps legacy strata",
  body: "# codebase-archeologist",
  color: undefined,
  model: { model: "grok-code-fast-1" },
  targetOverride: {},
  skills: ["testing"],
  allowedSkills: ["testing"],
  allowedTools: ["read"],
  toolBindings: [],
  manifest: {
    traits: [{ id: "forge:survey", ref: "survey" }],
    modelBindings: { modelspace: "forge:models", profile: "fast" },
  },
};

const manifest = () =>
  buildCompileManifestForTarget({
    base: emptyCompileManifest(),
    registry: registry(),
    target: "grok",
    scope: "project",
    composed: [composed],
    cacheDescriptors: new Map([["codebase-archeologist", descriptor]]),
  });

describe("workflow refs emitter", () => {
  test("renders literal agent refs from the compile manifest", () => {
    const output = renderWorkflowAgentsModule({ registry: registry(), manifest: manifest() });

    expect(output).toContain("Generated by Prism. Do not edit.");
    expect(output).toContain('"forge": {');
    expect(output).toContain('"codebaseArcheologist":');
    expect(output).toContain('kind: "agent-ref"');
    expect(output).toContain('name: "codebase-archeologist"');
    expect(output).toContain('sourcePath: "/tmp/forge/agents/codebase-archeologist.agent.ts"');
    expect(output).toContain('installs: ["grok"]');
    expect(output).toContain('as const satisfies Record<string, Record<string, WorkflowAgentRef>>');
  });

  test("plans a project .prism desired root for the sync engine", () => {
    const projectPath = "/tmp/workspace";
    const desired = planWorkflowRefsEmit({ projectPath, registry: registry(), manifest: manifest() });

    expect(desired.harness).toBe(WORKFLOW_REFS_HARNESS);
    expect(desired.root).toBe(workflowRefsRoot(projectPath));
    expect(desired.files).toHaveLength(1);
    expect(desired.files[0]?.targetPath).toBe(workflowAgentsPath(projectPath));
    expect(desired.files[0]?.plugin).toBe(WORKFLOW_REFS_HARNESS);
    expect(desired.regions).toEqual([]);
  });
});
