import { describe, expect, test } from "bun:test";
import { buildCompileManifestForTarget, emptyCompileManifest } from "./compile-manifest.js";
import type { AgentCacheDescriptor } from "./cache.js";
import type { ComposedAgent } from "./compose.js";
import { emptyRegistry } from "./registry.js";
import { Agent } from "./sources.js";
import {
  planWorkflowRefsEmit,
  renderWorkflowAgentsModule,
  renderWorkflowModelsModule,
  renderWorkflowSkillsModule,
  workflowAgentsPath,
  workflowModelsPath,
  workflowSkillsPath,
  workflowRefsRoot,
  WORKFLOW_REFS_HARNESS,
} from "./workflow-refs-emitter.js";

const registry = () => {
  const registry = emptyRegistry("/tmp/forge", "forge", "1.0.0");
  registry.agents.set("codebase-archeologist", new Agent({
    name: "codebase-archeologist",
    sourcePath: "/tmp/forge/agents/codebase-archeologist.agent.ts",
    description: "Maps legacy strata",
    identity: "builder",
    traits: [],
    access: { tools: [], toolGroups: [], skills: [] },
    skills: [],
    targets: {},
  }));
  return registry;
};

const descriptor: AgentCacheDescriptor = {
  key: "codebase-archeologist-key",
  sourceHash: "a".repeat(64),
  contextHash: "context",
  inputs: [{ plugin: "forge", path: "agents/codebase-archeologist.agent.ts", contentHash: "a".repeat(64) }],
};

const composed: ComposedAgent = {
  name: "codebase-archeologist",
  description: "Maps legacy strata",
  body: "# codebase-archeologist",
  color: undefined,
  model: { model: "grok-code-fast-1" },
  targetOverride: {},
  skills: ["testing"],
  allowedSkills: ["testing"],
  allowedTools: ["read"],
  toolBindings: [],
  manifest: {
    traits: [{ id: "forge:survey", ref: "survey" }],
    modelBindings: { modelspace: "forge:models", profile: "fast" },
  },
};

const manifest = () =>
  buildCompileManifestForTarget({
    base: emptyCompileManifest(),
    registry: registry(),
    target: "grok",
    scope: "project",
    composed: [composed],
    cacheDescriptors: new Map([["codebase-archeologist", descriptor]]),
  });

describe("workflow refs emitter", () => {
  test("renders literal agent refs from the compile manifest", () => {
    const output = renderWorkflowAgentsModule({ manifest: manifest() });

    expect(output).toContain("Generated by Prism. Do not edit.");
    expect(output).toContain('"forge": {');
    expect(output).toContain('"codebaseArcheologist":');
    expect(output).toContain('kind: "agent-ref"');
    expect(output).toContain('name: "codebase-archeologist"');
    expect(output).not.toContain("sourcePath");
    expect(output).toContain('installs: ["grok"]');
    expect(output).toContain('as const satisfies Record<string, Record<string, WorkflowAgentRef>>');
  });

  test("renders literal model profile refs from the compile manifest (no source paths)", () => {
    const output = renderWorkflowModelsModule({ manifest: manifest() });

    expect(output).toContain("Generated by Prism. Do not edit.");
    expect(output).toContain('"forge": {');
    expect(output).toContain('"models": {');
    expect(output).toContain('"fast":');
    expect(output).toContain('kind":"model-profile-ref"');
    expect(output).toContain('plugin":"forge"');
    expect(output).toContain('modelspace":"models"');
    expect(output).toContain('profile":"fast"');
    expect(output).not.toContain("sourcePath");
    expect(output).toContain('as const satisfies Record<string, Record<string, Record<string, WorkflowModelProfileRef>>>');
    expect(output).toContain("WorkflowModelspaceRef");
    expect(output).toContain("WorkflowModelProfileRef");
  });

  test("plans a project .prism desired root for the sync engine", () => {
    const projectPath = "/tmp/workspace";
    const desired = planWorkflowRefsEmit({ projectPath, manifest: manifest() });

    expect(desired.harness).toBe(WORKFLOW_REFS_HARNESS);
    expect(desired.root).toBe(workflowRefsRoot(projectPath));
    expect(desired.files).toHaveLength(3);
    expect(desired.files[0]?.targetPath).toBe(workflowAgentsPath(projectPath));
    expect(desired.files[0]?.plugin).toBe(WORKFLOW_REFS_HARNESS);
    expect(desired.files[1]?.targetPath).toBe(workflowModelsPath(projectPath));
    expect(desired.files[1]?.plugin).toBe(WORKFLOW_REFS_HARNESS);
    expect(desired.files[2]?.targetPath).toBe(workflowSkillsPath(projectPath));
    expect(desired.files[2]?.plugin).toBe(WORKFLOW_REFS_HARNESS);
    expect(desired.regions).toEqual([]);
  });

  test("renders literal skill and skillspace refs (managed vs skillspace, bare vs prefixed, no sourcePath)", () => {
    // Use build to populate; pass space-form and prefixed/bare in composed.skills to exercise parse + classify
    const mixedManifest = buildCompileManifestForTarget({
      base: emptyCompileManifest(),
      registry: registry(),
      target: "grok",
      scope: "project",
      composed: [
        {
          ...composed,
          skills: ["testing", "forge:build", "agent-core:core-skills/testing"],
          allowedSkills: ["testing", "forge:build", "agent-core:core-skills/testing"],
        },
      ],
      cacheDescriptors: new Map([["codebase-archeologist", descriptor]]),
    });

    const output = renderWorkflowSkillsModule({ manifest: mixedManifest });

    expect(output).toContain("Generated by Prism. Do not edit.");
    expect(output).toContain("WorkflowManagedSkillRef");
    expect(output).toContain("WorkflowSkillspaceRef");
    expect(output).toContain('"forge": {');
    expect(output).toContain('kind":"managed-skill-ref"');
    expect(output).toContain('"name":"testing"');
    expect(output).toContain('"name":"build"');
    expect(output).toContain('kind":"skillspace-ref"');
    expect(output).toContain('"skillspace":"core-skills"');
    expect(output).toContain('"skills":["testing"]');
    expect(output).not.toContain("sourcePath");
    expect(output).toContain('as const satisfies Record<string, Record<string, WorkflowManagedSkillRef | WorkflowSkillspaceRef>>');
  });

  test("empty manifest produces valid skills module with interfaces and empty skills", () => {
    const output = renderWorkflowSkillsModule({ manifest: emptyCompileManifest() });

    expect(output).toContain("Generated by Prism. Do not edit.");
    expect(output).toContain("export interface WorkflowManagedSkillRef");
    expect(output).toContain("export interface WorkflowSkillspaceRef");
    expect(output).toContain("export const skills = {");
    expect(output).not.toContain("sourcePath");
    expect(output).toContain("} as const satisfies Record<string, Record<string, WorkflowManagedSkillRef | WorkflowSkillspaceRef>>");
  });

  test("fallback derivation unions multiple skills per skillspace when top-level skills empty (bare manifest hit)", () => {
    const base = buildCompileManifestForTarget({
      base: emptyCompileManifest(),
      registry: registry(),
      target: "grok",
      scope: "project",
      composed: [
        {
          ...composed,
          skills: ["agent-core:core-skills/testing", "agent-core:core-skills/extra"],
          allowedSkills: ["agent-core:core-skills/testing", "agent-core:core-skills/extra"],
        },
      ],
      cacheDescriptors: new Map([["codebase-archeologist", descriptor]]),
    });
    // zero top-level to force fallback path (mirrors legacy/empty case; build normally populates)
    const bare = { ...base, modelspaces: {}, skills: {} } as typeof base;
    const output = renderWorkflowSkillsModule({ manifest: bare });

    expect(output).toContain("Generated by Prism. Do not edit.");
    expect(output).toContain('kind":"skillspace-ref"');
    expect(output).toContain('"skillspace":"core-skills"');
    // unioned + inner sorted, not dropped
    expect(output).toContain('"skills":["extra","testing"]');
    expect(output).not.toContain("sourcePath");
  });
});
