import { describe, expect, test } from "bun:test";
import { join } from "node:path";
import { buildCompileManifestForTarget, emptyCompileManifest } from "./compile-manifest.js";
import type { AgentCacheDescriptor } from "./cache.js";
import type { ComposedAgent } from "./compose.js";
import { emptyRegistry } from "./registry.js";
import { Agent } from "./sources.js";
import {
  planWorkflowRefsEmit,
  renderWorkflowAgentsModule,
  renderWorkflowModelsModule,
  renderWorkflowOrbitsModule,
  renderWorkflowSkillsModule,
  renderWorkflowTraitsModule,
  renderWorkflowToolsModule,
  workflowAgentsPath,
  workflowModelsPath,
  workflowOrbitsPath,
  workflowSkillsPath,
  workflowTraitsPath,
  workflowToolsPath,
  workflowRefsRoot,
  WORKFLOW_REFS_HARNESS,
} from "./workflow-refs-emitter.js";

const registry = () => {
  const registry = emptyRegistry("/tmp/forge", "forge", "1.0.0");
  registry.agents.set("codebase-archeologist", new Agent({
    name: "codebase-archeologist",
    sourcePath: "/tmp/forge/agents/codebase-archeologist.agent.ts",
    description: "Maps legacy strata",
    identity: "builder",
    traits: [],
    access: { tools: [], toolGroups: [], skills: [] },
    skills: [],
    targets: {},
  }));
  return registry;
};

const descriptor: AgentCacheDescriptor = {
  key: "codebase-archeologist-key",
  sourceHash: "a".repeat(64),
  contextHash: "context",
  inputs: [{ plugin: "forge", path: "agents/codebase-archeologist.agent.ts", contentHash: "a".repeat(64) }],
};

const composed: ComposedAgent = {
  name: "codebase-archeologist",
  description: "Maps legacy strata",
  body: "# codebase-archeologist",
  color: undefined,
  model: { model: "grok-code-fast-1" },
  targetOverride: {},
  skills: ["testing"],
  allowedSkills: ["testing"],
  allowedTools: ["read"],
  toolBindings: [],
  manifest: {
    traits: [{ id: "forge:survey", ref: "survey" }],
    modelBindings: { modelspace: "forge:models", profile: "fast" },
  },
};

const manifest = () =>
  buildCompileManifestForTarget({
    base: emptyCompileManifest(),
    registry: registry(),
    target: "grok",
    scope: "project",
    composed: [composed],
    cacheDescriptors: new Map([["codebase-archeologist", descriptor]]),
  });

describe("workflow refs emitter", () => {
  test("renders literal agent refs from the compile manifest", () => {
    const output = renderWorkflowAgentsModule({ manifest: manifest() });

    expect(output).toContain("Generated by Prism. Do not edit.");
    expect(output).toContain('"forge": {');
    expect(output).toContain('"codebaseArcheologist":');
    expect(output).toContain('kind: "agent-ref"');
    expect(output).toContain('name: "codebase-archeologist"');
    expect(output).not.toContain("sourcePath");
    expect(output).toContain('installs: ["grok"]');
    expect(output).toContain('"targets":{"grok":{"model":"grok-code-fast-1"}}');
    expect(output).toContain('as const satisfies Record<string, Record<string, WorkflowAgentRef>>');
  });

  test("renders literal model profile refs from the compile manifest (no source paths)", () => {
    const output = renderWorkflowModelsModule({ manifest: manifest() });

    expect(output).toContain("Generated by Prism. Do not edit.");
    expect(output).toContain('"forge": {');
    expect(output).toContain('"models": {');
    expect(output).toContain('"fast":');
    expect(output).toContain('kind":"model-profile-ref"');
    expect(output).toContain('plugin":"forge"');
    expect(output).toContain('modelspace":"models"');
    expect(output).toContain('profile":"fast"');
    expect(output).toContain('targets":{"grok":{"model":"grok-code-fast-1"}}');
    expect(output).not.toContain("sourcePath");
    expect(output).toContain('as const satisfies Record<string, Record<string, Record<string, WorkflowModelProfileRef>>>');
    expect(output).toContain("WorkflowModelspaceRef");
    expect(output).toContain("WorkflowModelProfileRef");
  });

  test("renders modelspace profiles not referenced by agents", () => {
    const base = manifest();
    const output = renderWorkflowModelsModule({
      manifest: {
        ...base,
        modelspaces: {
          ...base.modelspaces,
          "forge:models": {
            plugin: "forge",
            modelspace: "models",
            profiles: ["fast", "unreferenced"],
            profilesData: {
              fast: { grok: { model: "grok-code-fast-1" } },
              unreferenced: { opencode: { model: "provider/unreferenced" } },
            },
          },
        },
      },
    });

    expect(output).toContain('"fast":');
    expect(output).toContain('"unreferenced":');
    expect(output).toContain('"provider/unreferenced"');
  });

  test("plans a machine-global, project-keyed generated desired root for the sync engine", () => {
    const prismHome = "/tmp/prism-home";
    const projectKey = "workspace-key";
    const desired = planWorkflowRefsEmit({ prismHome, projectKey, manifest: manifest() });

    expect(desired.harness).toBe(WORKFLOW_REFS_HARNESS);
    expect(desired.root).toBe(workflowRefsRoot(prismHome, projectKey));
    // Refs are Prism-owned, never in the project tree: under ~/.prism/state.
    expect(desired.root).toContain(join("state", "projects", projectKey, "generated"));
    expect(desired.root).not.toContain(".prism/generated/workflows");
    expect(desired.files).toHaveLength(6);
    expect(desired.files[0]?.targetPath).toBe(workflowAgentsPath(prismHome, projectKey));
    expect(desired.files[0]?.plugin).toBe(WORKFLOW_REFS_HARNESS);
    expect(desired.files[1]?.targetPath).toBe(workflowModelsPath(prismHome, projectKey));
    expect(desired.files[1]?.plugin).toBe(WORKFLOW_REFS_HARNESS);
    expect(desired.files[2]?.targetPath).toBe(workflowSkillsPath(prismHome, projectKey));
    expect(desired.files[2]?.plugin).toBe(WORKFLOW_REFS_HARNESS);
    expect(desired.files[3]?.targetPath).toBe(workflowTraitsPath(prismHome, projectKey));
    expect(desired.files[3]?.plugin).toBe(WORKFLOW_REFS_HARNESS);
    expect(desired.files[4]?.targetPath).toBe(workflowOrbitsPath(prismHome, projectKey));
    expect(desired.files[4]?.plugin).toBe(WORKFLOW_REFS_HARNESS);
    expect(desired.files[5]?.targetPath).toBe(workflowToolsPath(prismHome, projectKey));
    expect(desired.files[5]?.plugin).toBe(WORKFLOW_REFS_HARNESS);
    expect(desired.regions).toEqual([]);
  });

  test("renders literal skill and skillspace refs (managed vs skillspace, bare vs prefixed, no sourcePath)", () => {
    // Use build to populate; pass space-form and prefixed/bare in composed.skills to exercise parse + classify
    const mixedManifest = buildCompileManifestForTarget({
      base: emptyCompileManifest(),
      registry: registry(),
      target: "grok",
      scope: "project",
      composed: [
        {
          ...composed,
          skills: ["testing", "forge:build", "agent-core:core-skills/testing"],
          allowedSkills: ["testing", "forge:build", "agent-core:core-skills/testing"],
        },
      ],
      cacheDescriptors: new Map([["codebase-archeologist", descriptor]]),
    });

    const output = renderWorkflowSkillsModule({ manifest: mixedManifest });

    expect(output).toContain("Generated by Prism. Do not edit.");
    expect(output).toContain("WorkflowManagedSkillRef");
    expect(output).toContain("WorkflowSkillspaceRef");
    expect(output).toContain('"forge": {');
    expect(output).toContain('kind":"managed-skill-ref"');
    expect(output).toContain('"name":"testing"');
    expect(output).toContain('"name":"build"');
    expect(output).toContain('kind":"skillspace-ref"');
    expect(output).toContain('"skillspace":"core-skills"');
    expect(output).toContain('"skills":["testing"]');
    expect(output).not.toContain("sourcePath");
    expect(output).toContain('as const satisfies Record<string, Record<string, WorkflowManagedSkillRef | WorkflowSkillspaceRef>>');
  });

  test("empty manifest produces valid skills module with interfaces and empty skills", () => {
    const output = renderWorkflowSkillsModule({ manifest: emptyCompileManifest() });

    expect(output).toContain("Generated by Prism. Do not edit.");
    expect(output).toContain("export interface WorkflowManagedSkillRef");
    expect(output).toContain("export interface WorkflowSkillspaceRef");
    expect(output).toContain("export const skills = {");
    expect(output).not.toContain("sourcePath");
    expect(output).toContain("} as const satisfies Record<string, Record<string, WorkflowManagedSkillRef | WorkflowSkillspaceRef>>");
  });

  test("fallback derivation unions multiple skills per skillspace when top-level skills empty (bare manifest hit)", () => {
    const base = buildCompileManifestForTarget({
      base: emptyCompileManifest(),
      registry: registry(),
      target: "grok",
      scope: "project",
      composed: [
        {
          ...composed,
          skills: ["agent-core:core-skills/testing", "agent-core:core-skills/extra"],
          allowedSkills: ["agent-core:core-skills/testing", "agent-core:core-skills/extra"],
        },
      ],
      cacheDescriptors: new Map([["codebase-archeologist", descriptor]]),
    });
    // zero top-level to force fallback path (mirrors legacy/empty case; build normally populates)
    const bare = { ...base, modelspaces: {}, skills: {} } as typeof base;
    const output = renderWorkflowSkillsModule({ manifest: bare });

    expect(output).toContain("Generated by Prism. Do not edit.");
    expect(output).toContain('kind":"skillspace-ref"');
    expect(output).toContain('"skillspace":"core-skills"');
    // unioned + inner sorted, not dropped
    expect(output).toContain('"skills":["extra","testing"]');
    expect(output).not.toContain("sourcePath");
  });

  test("renders literal trait refs from the compile manifest (deterministic grouped, cross-plugin ids ok, no sourcePath)", () => {
    const output = renderWorkflowTraitsModule({ manifest: manifest() });

    expect(output).toContain("Generated by Prism. Do not edit.");
    expect(output).toContain('"forge": {');
    expect(output).toContain('"survey":');
    expect(output).toContain('kind":"trait-ref"');
    expect(output).toContain('"id":"forge:survey"');
    expect(output).toContain('"ref":"survey"');
    expect(output).not.toContain("sourcePath");
    expect(output).toContain('as const satisfies Record<string, Record<string, WorkflowTraitRef>>');
  });

  test("renders deterministic grouped trait refs for cross-plugin ids", () => {
    const crossManifest = buildCompileManifestForTarget({
      base: emptyCompileManifest(),
      registry: registry(),
      target: "grok",
      scope: "project",
      composed: [
        {
          ...composed,
          manifest: {
            traits: [
              { id: "forge:survey", ref: "survey" },
              { id: "core:committable", ref: "committable" },
            ],
            modelBindings: { modelspace: "forge:models", profile: "fast" },
          },
        },
      ],
      cacheDescriptors: new Map([["codebase-archeologist", descriptor]]),
    });

    const output = renderWorkflowTraitsModule({ manifest: crossManifest });

    expect(output).toContain("Generated by Prism. Do not edit.");
    expect(output).toContain('"core": {');
    expect(output).toContain('"committable":');
    expect(output).toContain('"forge": {');
    expect(output).toContain('"survey":');
    expect(output).toContain('kind: "trait-ref"');
    expect(output).not.toContain("sourcePath");
    // plugins grouped deterministically (core before forge)
    const coreIdx = output.indexOf('"core"');
    const forgeIdx = output.indexOf('"forge"');
    expect(coreIdx).toBeGreaterThan(-1);
    expect(forgeIdx).toBeGreaterThan(coreIdx);
  });

  test("empty manifest produces valid traits module with interfaces and empty traits", () => {
    const output = renderWorkflowTraitsModule({ manifest: emptyCompileManifest() });

    expect(output).toContain("Generated by Prism. Do not edit.");
    expect(output).toContain("export interface WorkflowTraitRef");
    expect(output).toContain("export const traits = {");
    expect(output).not.toContain("sourcePath");
    expect(output).toContain("} as const satisfies Record<string, Record<string, WorkflowTraitRef>>");
  });

  test("renders literal orbit refs from the compile manifest (deterministic grouped, no sourcePath)", () => {
    // The manifest() builder produces agents only; use explicit build with orbits in base to simulate post-update manifest
    const orbitManifest = buildCompileManifestForTarget({
      base: { ...emptyCompileManifest(), orbits: { "forge:delivery-contract": { plugin: "forge", name: "delivery-contract" } } } as any,
      registry: registry(),
      target: "grok",
      scope: "project",
      composed: [composed],
      cacheDescriptors: new Map([["codebase-archeologist", descriptor]]),
    });

    const output = renderWorkflowOrbitsModule({ manifest: orbitManifest });

    expect(output).toContain("Generated by Prism. Do not edit.");
    expect(output).toContain('"forge": {');
    expect(output).toContain('"deliveryContract":');
    expect(output).toContain('"kind":"orbit-ref"');
    expect(output).toContain('"name":"delivery-contract"');
    expect(output).not.toContain("sourcePath");
    expect(output).not.toContain("phase");
    expect(output).toContain('as const satisfies Record<string, Record<string, WorkflowOrbitRef>>');
  });

  test("renders deterministic grouped orbit refs for cross-plugin", () => {
    const crossManifest = buildCompileManifestForTarget({
      base: { ...emptyCompileManifest(), orbits: {
        "forge:delivery-contract": { plugin: "forge", name: "delivery-contract" },
        "core:experiment": { plugin: "core", name: "experiment" },
      } } as any,
      registry: registry(),
      target: "grok",
      scope: "project",
      composed: [composed],
      cacheDescriptors: new Map([["codebase-archeologist", descriptor]]),
    });

    const output = renderWorkflowOrbitsModule({ manifest: crossManifest });

    expect(output).toContain("Generated by Prism. Do not edit.");
    expect(output).toContain('"core": {');
    expect(output).toContain('"experiment":');
    expect(output).toContain('"forge": {');
    expect(output).toContain('"deliveryContract":');
    expect(output).toContain('kind: "orbit-ref"');
    expect(output).not.toContain("sourcePath");
    // plugins grouped deterministically (core before forge)
    const coreIdx = output.indexOf('"core"');
    const forgeIdx = output.indexOf('"forge"');
    expect(coreIdx).toBeGreaterThan(-1);
    expect(forgeIdx).toBeGreaterThan(coreIdx);
  });

  test("empty manifest produces valid orbits module with interfaces and empty orbits", () => {
    const output = renderWorkflowOrbitsModule({ manifest: emptyCompileManifest() });

    expect(output).toContain("Generated by Prism. Do not edit.");
    expect(output).toContain("export interface WorkflowOrbitRef");
    expect(output).toContain("export const orbits = {");
    expect(output).not.toContain("sourcePath");
    expect(output).toContain("} as const satisfies Record<string, Record<string, WorkflowOrbitRef>>");
  });

  test("renders literal tool and toolspace refs from the compile manifest (deterministic camel keys, cross-plugin, no sourcePath)", () => {
    const toolManifest = buildCompileManifestForTarget({
      base: emptyCompileManifest(),
      registry: registry(),
      target: "grok",
      scope: "project",
      composed: [{
        ...composed,
        toolBindings: [
          { kind: "permission", logicalName: "commit_work", toolPluginName: "forge", toolName: "commit-work" },
          { kind: "permission", logicalName: "create_glyph", toolPluginName: "protocol-core", toolName: "create_glyph" },
          { kind: "permission", logicalName: "run_shell", toolPluginName: "agent-core", toolName: "workspace-tools/run_shell" },
        ],
      } as any],
      cacheDescriptors: new Map([["codebase-archeologist", descriptor]]),
    });

    const output = renderWorkflowToolsModule({ manifest: toolManifest });

    expect(output).toContain("Generated by Prism. Do not edit.");
    expect(output).toContain("WorkflowCanonicalToolRef");
    expect(output).toContain("WorkflowToolspaceToolRef");
    expect(output).toContain('"forge": {');
    expect(output).toContain('"commitWork":');
    expect(output).toContain('kind":"canonical-tool-ref"');
    expect(output).toContain('"name":"commit-work"');
    expect(output).toContain('"protocolCore": {');
    expect(output).toContain('"createGlyph":');
    expect(output).toContain('"agentCore": {');
    expect(output).toContain('"workspaceTools": {');
    expect(output).toContain('"runShell":');
    expect(output).toContain('kind":"toolspace-tool-ref"');
    expect(output).toContain('"toolspace":"workspace-tools"');
    expect(output).not.toContain("sourcePath");
    expect(output).not.toContain("input");
    expect(output).not.toContain("handle");
    expect(output).toContain('as const satisfies Record<string, Record<string, WorkflowCanonicalToolRef | Record<string, WorkflowToolspaceToolRef>>>');
  });

  test("empty manifest produces valid tools module with interfaces and empty tools", () => {
    const output = renderWorkflowToolsModule({ manifest: emptyCompileManifest() });

    expect(output).toContain("Generated by Prism. Do not edit.");
    expect(output).toContain("export interface WorkflowCanonicalToolRef");
    expect(output).toContain("export interface WorkflowToolspaceToolRef");
    expect(output).toContain("export const tools = {");
    expect(output).not.toContain("sourcePath");
    expect(output).toContain("} as const satisfies Record<string, Record<string, WorkflowCanonicalToolRef | Record<string, WorkflowToolspaceToolRef>>>");
  });

  test("renders deterministic grouped tool refs for cross-plugin and mixed canon+toolspace under one plugin", () => {
    const crossManifest = buildCompileManifestForTarget({
      base: emptyCompileManifest(),
      registry: registry(),
      target: "grok",
      scope: "project",
      composed: [{
        ...composed,
        toolBindings: [
          { kind: "permission", logicalName: "exp", toolPluginName: "core", toolName: "experiment" },
          { kind: "permission", logicalName: "cw", toolPluginName: "forge", toolName: "commit-work" },
          { kind: "permission", logicalName: "rs", toolPluginName: "forge", toolName: "workspace-tools/run_shell" },
        ],
      } as any],
      cacheDescriptors: new Map([["codebase-archeologist", descriptor]]),
    });

    const output = renderWorkflowToolsModule({ manifest: crossManifest });

    expect(output).toContain("Generated by Prism. Do not edit.");
    expect(output).toContain('"core": {');
    expect(output).toContain('"experiment":');
    expect(output).toContain('"forge": {');
    expect(output).toContain('"commitWork":');
    expect(output).toContain('"workspaceTools": {');
    expect(output).toContain('"runShell"');
    expect(output).toContain('kind: "canonical-tool-ref"');
    expect(output).toContain('kind: "toolspace-tool-ref"');
    expect(output).not.toContain("sourcePath");
    // plugins grouped deterministically (core before forge)
    const coreIdx = output.indexOf('"core"');
    const forgeIdx = output.indexOf('"forge"');
    expect(coreIdx).toBeGreaterThan(-1);
    expect(forgeIdx).toBeGreaterThan(coreIdx);
  });

  test("fallback derivation collects multiple tools per toolspace without loss when top-level tools empty", () => {
    const base = buildCompileManifestForTarget({
      base: emptyCompileManifest(),
      registry: registry(),
      target: "grok",
      scope: "project",
      composed: [
        {
          ...composed,
          toolBindings: [
            { kind: "permission", logicalName: "read", toolPluginName: "agent-core", toolName: "read" },
            { kind: "permission", logicalName: "grep", toolPluginName: "agent-core", toolName: "grep" },
          ],
          // simulate grants in composed
        } as any,
      ],
      cacheDescriptors: new Map([["codebase-archeologist", descriptor]]),
    });
    // simulate bare manifest without top-level tools (force fallback)
    // patch grants to use space form
    const patched = {
      ...base,
      agents: {
        ...base.agents,
        "forge:codebase-archeologist": {
          ...base.agents["forge:codebase-archeologist"]!,
          composed: {
            ...base.agents["forge:codebase-archeologist"]!.composed,
            grants: { tools: ["agent-core:workspace-tools/read", "agent-core:workspace-tools/grep"], skills: [] },
          },
        },
      },
      tools: {},
    } as any;
    const output = renderWorkflowToolsModule({ manifest: patched });

    expect(output).toContain("Generated by Prism. Do not edit.");
    expect(output).toContain('kind":"toolspace-tool-ref"');
    expect(output).toContain('"workspaceTools"');
    // multiple under same toolspace, not dropped
    expect(output).toContain('"read"');
    expect(output).toContain('"grep"');
    expect(output).not.toContain("sourcePath");
  });

  test("manifest.tools (populated from grants) yields source-free deterministic tools ref output", () => {
    const withGrants = buildCompileManifestForTarget({
      base: emptyCompileManifest(),
      registry: registry(),
      target: "grok",
      scope: "project",
      composed: [
        {
          ...composed,
          toolBindings: [
            { kind: "permission", logicalName: "run_shell", toolPluginName: "agent-core", toolName: "workspace-tools/run_shell" },
            { kind: "permission", logicalName: "create_glyph", toolPluginName: "protocol-core", toolName: "create_glyph" },
          ],
        } as any,
      ],
      cacheDescriptors: new Map([["codebase-archeologist", descriptor]]),
    });
    // ensure top-level tools got populated by build (from grants)
    expect(Object.keys(withGrants.tools || {}).length).toBeGreaterThan(0);
    const output = renderWorkflowToolsModule({ manifest: withGrants });

    expect(output).toContain("Generated by Prism. Do not edit.");
    expect(output).toContain('kind":"toolspace-tool-ref"');
    expect(output).toContain('"protocolCore"');
    expect(output).toContain('"createGlyph"');
    expect(output).not.toContain("sourcePath");
    expect(output).not.toContain("/tmp");
    expect(output).not.toContain(".tool.ts");
  });
});
