#!/usr/bin/env bun
/**
 * Build @skastr0/prism-packager by copying the transitive TypeScript source
 * graph rooted at src/packager.ts into packages/prism-packager/src/.
 *
 * Why copy sources (not a single-file bundle):
 * - The compile pipeline loads TypeScript via createRequire + path resolution
 *   and uses Bun.build for hook/tool emission. Mega-bundles break those seams.
 * - Consumers already require Bun (engines.bun); shipping .ts is honest and
 *   keeps import.meta.url / runtime-deps resolution working.
 *
 * Source of truth remains monorepo src/. This package is a publishable snapshot.
 */
import { cp, mkdir, rm, writeFile } from "node:fs/promises";
import { existsSync, readFileSync, statSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const REPO_ROOT = fileURLToPath(new URL("..", import.meta.url));
const SRC_ROOT = resolve(REPO_ROOT, "src");
const PACKAGE_ROOT = resolve(REPO_ROOT, "packages", "prism-packager");
const OUT_SRC = resolve(PACKAGE_ROOT, "src");
const ENTRY = resolve(SRC_ROOT, "packager.ts");

const resolveImport = (fromFile: string, spec: string): string | null => {
  if (!spec.startsWith(".")) return null;
  const raw = resolve(dirname(fromFile), spec);
  const candidates = [
    raw,
    `${raw}.ts`,
    `${raw}.tsx`,
    raw.replace(/\.js$/, ".ts"),
    raw.replace(/\.js$/, ".tsx"),
    join(raw, "index.ts"),
  ];
  for (const candidate of candidates) {
    try {
      if (statSync(candidate).isFile()) return candidate;
    } catch {
      // try next
    }
  }
  return null;
};

const collectSourceGraph = (entry: string): string[] => {
  const seen = new Set<string>();
  const queue = [entry];
  while (queue.length > 0) {
    const file = queue.pop();
    if (!file || seen.has(file) || !file.startsWith(SRC_ROOT)) continue;
    if (file.endsWith(".test.ts") || file.endsWith(".test.tsx")) continue;
    seen.add(file);
    const text = readFileSync(file, "utf8");
    for (const match of text.matchAll(/from\s+["']([^"']+)["']/g)) {
      const resolved = resolveImport(file, match[1] ?? "");
      if (resolved) queue.push(resolved);
    }
    for (const match of text.matchAll(/import\s*\(\s*["']([^"']+)["']\s*\)/g)) {
      const resolved = resolveImport(file, match[1] ?? "");
      if (resolved) queue.push(resolved);
    }
  }
  return [...seen].sort();
};

const PUBLIC_INDEX = `/**
 * @skastr0/prism-packager public entry.
 * Generated by scripts/build-prism-packager.ts — do not edit by hand.
 */
export {
  packagePluginForTarget,
  packagePluginForTargets,
  formatPackageOperations,
  type PackageTargetOptions,
  type PackageTargetsOptions,
  type PackageWriteOperation,
  type PackageResult,
} from "./packager.js";

export type { DesiredFile, DesiredRegion, DesiredRoot } from "./sync/desired.js";
export type { HarnessId, HarnessScope } from "./types.js";
`;

const main = async (): Promise<void> => {
  if (!existsSync(ENTRY)) {
    throw new Error(`Missing packager entry: ${ENTRY}`);
  }

  const files = collectSourceGraph(ENTRY);
  if (files.length === 0) {
    throw new Error("Packager source graph is empty");
  }

  await rm(OUT_SRC, { recursive: true, force: true });
  await mkdir(OUT_SRC, { recursive: true });

  for (const file of files) {
    const rel = relative(SRC_ROOT, file);
    const dest = join(OUT_SRC, rel);
    await mkdir(dirname(dest), { recursive: true });
    await cp(file, dest);
  }

  await writeFile(join(OUT_SRC, "index.ts"), PUBLIC_INDEX, "utf8");

  // Guard: refuse to ship CLI/TUI entrypoints if the graph ever reaches them.
  const forbidden = files.filter((file) => {
    const rel = relative(SRC_ROOT, file);
    return (
      rel === "cli.ts" ||
      rel.startsWith("plugins-tui/") ||
      rel.startsWith("configure/") ||
      rel === "workflow-tui.tsx" ||
      rel.startsWith("workflow-tui.")
    );
  });
  if (forbidden.length > 0) {
    throw new Error(
      `Packager graph includes forbidden CLI/TUI modules:\n${forbidden.map((f) => relative(REPO_ROOT, f)).join("\n")}`,
    );
  }

  console.log(
    `build-prism-packager: copied ${files.length} modules + index.ts -> packages/prism-packager/src/`,
  );
};

await main();
